- autopush/endpoint.py
- autopush/tests/test_endpoint.py
Other small fixes...
* Use the current time if the `version` param is omitted, not a number, or negative to match the Go server behavior.
* Pass along the `node_id` for the "client busy" case, not the "routing failure" case.
* Handle empty `node_id` fields in `_process_jumped_client`.
> Add endpoint tests

- autopush/endpoint.py
- autopush/main.py
- autopush/settings.py
- autopush/tests/test_endpoint.py
- autopush/tests/test_main.py
This is a late fix request from releng. CORS support is only required for DEV and STAGE environments (thus why it defaults to "off")
Operations:
Note that CORS is only enabled if you run `autoendpoint --cors` or with environment `ALLOW_CORS`
> Add optional CORS support to Autopush

- autopush/tests/test_websocket.py
- autopush/websocket.py
* These also need to use ap_settings to avoid property stomping
@bbangert r?
> Fix for #13 websocket routing and notif handlers

- Makefile
- README.rst
Mostly for selfish reasons, since @jrconlin and @bbangert both use Linux...
* `cffi@0.9.2` requires PyPy >= 2.5.1.
* OS X doesn't ship with `wget` by default, but `curl -O` is equivalent for our purposes. :crying_cat_face:
* `ARCHFLAGS`, `LDFLAGS`, and `CFLAGS` should be set, to avoid linking against the ancient system-bundled OpenSSL.
> Note required PyPy version; add OS X instructions

- autopush/metrics.py
- autopush/tests/test_metrics.py
Adding the `host` argument to each metric allows it to aggregate the metric with everything else it knows about that host.
> Datadog features

- .dockerignore
- Dockerfile.automock
- Makefile
- automock/boto.cfg
- automock/supervisord.conf
- autopush/main.py
- autopush/settings.py
- autopush/tests/test_main.py
- autopush/utils.py
- tox.ini
Alternative implementation of #40, using Supervisor instead of a unified `autonode`. This requires mounting a config file into the container, since `autopush` and `autoendpoint` rely on shared environment variables (e.g., `port`, `ssl_key`, `ssl_cert`).
> Add an `automock` script

- autopush/logging.py
@bbangert r?
This was suggested by @whd to more closely meet our logging standard.
> logging: move message_type out to Type field

- autopush/db.py
Easy to reproduce by running the smoke tests with a mock Moto server. @bbangert already trapped `JSONResponseError` in `get_uaid`; this just adds the same logic to `get_connection`.
> Work around a Moto bug in `get_connection`

- autopush/health.py
- autopush/main.py
- autopush/tests/test_health.py
Closes #34.
I thought about reusing `preflight_check` for this...but it would be really inconvenient if folks could use up our provisioned throughput with a simple `while true; do curl https://autopush.server/health; done`.
> Add a health handler with DynamoDB connection status

- Makefile
- autopush/main.py
- autopush/settings.py
- autopush/tests/test_websocket.py
- autopush/websocket.py
- configs/autopush_endpoint.ini
`pong_delay` waits to respond to client pings, to work around clients that enter a ping loop.
> Add a `pong_delay` option for excessive pings

- CHANGELOG.rst
- README.rst
- autopush/tests/test_main.py
- autopush/utils.py
I previously didn't see the two lines missing since a blanket except statement caught the import error. Python 2.7.7 and above have compare_digest, the rest don't. I've also bumped the pypy dependency to ensure it requires a Python appropriate, and removed the try/except that wasn't needed.
> * Increase test coverage of utils for 100% test coverage.

- autopush/main.py
Add max connections as a config argument to avoid server load over a
safe value. In case of a DOS attack, this would avoid a failure of
existing connections.
This PR doesn't include tests, since I couldn't figure a way to test it. I 
understand that a test for this would become a test for Autobahn, 
which would be the library's responsibility?
When I set the limit to 1, this results in a `503` with the message:
`maximum number of connections reached` on a second connection.
When the old connection is closed, a connection spot is open again. The
default  `0`, removes any soft limits on the number of connections.
Ref #104
> Support for limiting maximum concurrent connections

- CHANGELOG.rst
- autopush/db.py
- autopush/endpoint.py
- autopush/router/interface.py
- autopush/router/webpush.py
- autopush/tests/test_db.py
- autopush/tests/test_endpoint.py
- autopush/tests/test_router.py
- autopush/tests/test_websocket.py
- autopush/websocket.py
Add WebPush TTL scheme per spec (as of July 28th 2015).
This is a relatively minor change to store the TTL value, and avoid storage of it if the TTL is set to 0. The spec is slightly ambiguous on whether a Location should still be returned if a TTL is 0 and it couldn't be delivered (such that no such resource exists, and its not clear if a NACK exists). So for now, no Location is returned if the message couldn't be delivered, the spec says POST always returns a 201 though, so, its still a 201.
To break off router execution if the TTL is 0, I threw a RouterException in the webpush router, and added a headers field for the possibility that in the future, a Location should still be returned in this case.
Closes #56.
> Add WebPush TTL's

- CHANGELOG.rst
- autopush/endpoint.py
- autopush/router/interface.py
- autopush/router/simple.py
- autopush/router/webpush.py
Use log_exception on RouterException to determine if it should be logged (and flagged in Sentry).
Don't log common exception use, where the exception is not actually an actionable bug.
Closes Issue #125.
> Remove excessive exception logging

- CHANGELOG.rst
- autopush/tests/test_endpoint.py
- autopush/tests/test_integration.py
- autopush/tests/test_websocket.py
- autopush/websocket.py
- test-requirements.txt
- tox.ini
Bug Fixes
---------
* Fix deferToLater to not call the function if it was cancelled using a
canceller function.
* Fix finish_webpush_notifications to not immediately call
process_notifications as that will be called as needed after ack's have been
completed.
* Fix process_ack to not call process_notifications when using webpush if there
are still remaining notifications to ack.
Features
--------
* Integrate simplepush_test smoke-test client with the main autopush test-suite
into the test-runner. Issue #119.
Closes #119.
> Integrate smoke-tests, also fixes bugs found as a result

- CHANGELOG.rst
- autopush/tests/test_websocket.py
- autopush/websocket.py
* Remove adaptive ping entirely. Send special close code and drop clients that
ping more frequently than 55 seconds (approx 1 min). This will result in
clients that ping too much being turned away for awhile, but will alleviate
data/battery issues in buggy mobile clients. Issue #103.
* Log all disconnects, whether they were clean, the code, and the reason.
Closes #103.
> Remove adaptive ping, log connection losses

- CHANGELOG.rst
- autopush/websocket.py
* Fix _notify_node to not attempt delivering to ourselves at the end of the
client connection.
> Add check to avoid delivering to ourselves.

- CHANGELOG.rst
- autopush/db.py
- autopush/endpoint.py
- autopush/router/webpush.py
- autopush/tests/test_db.py
- autopush/tests/test_endpoint.py
- autopush/tests/test_integration.py
- autopush/websocket.py
This lets folks use Web Push as if it were Simple Push. For that case, I don't think there's much point to sending an encrypted empty string.
Closes #132.
> Omit headers and data for empty messages

- CHANGELOG.rst
- autopush/endpoint.py
- autopush/tests/test_endpoint.py
This lets our tests make cross-origin requests directly.
> Expose Web Push headers for CORS requests

- CHANGELOG.rst
- autopush/main.py
Allow for servers to specify larger default message buffer sizes
(Current recommendation is to raise them to 3072 or larger until the
client lands which turns off client send of ChannelIDs as part of the
"hello")
r? @bbangert @kitcambridge
> Fix for #151 allow for larger cyclone messages

- autopush/main.py
"0" disables Autobahn's closing handshake timeout. This still nukes the connection if it hasn't been closed within 5 seconds, which seems reasonable.
> Add option for closing handshake timeout

- CHANGELOG.rst
- autopush/endpoint.py
- autopush/websocket.py
* Up default close handshake timer to 10 seconds for slower clients.
* Add channel id logging to endpoint.
@kitcambridge, @jrconlin r?
> Up close handshake and add chid logging to endpoint

- CHANGELOG.rst
- autopush/endpoint.py
- autopush/main.py
- autopush/router/simple.py
- autopush/router/webpush.py
- autopush/settings.py
- autopush/tests/test_endpoint.py
- autopush/tests/test_integration.py
- autopush/tests/test_router.py
Here's a sketch of a `DELETE` implementation for messages. Still needs tests, but I thought I'd extract what I have so far.
This only deletes messages from storage, not direct updates. I thought about having it handle those, too, but that'd mean an extra routing table read to look up the home node. That seems fine, since deleting a message sent to a connected client is inherently racy, and it's far more likely the message will be delivered before the connection node receives the "oops, don't send that" signal.
f? @bbangert @jrconlin
> Message deletion endpoint

- CHANGELOG.rst
- autopush/tests/test_websocket.py
- autopush/websocket.py
* Remove logging of sendClose, as its unactionable noise. Add metric for
sendClose success. Remove final verifyNuke as its never run in the several
months it was in, indicating that abortConnection is 100% effective.
Issue #161.
Closes #161.
@kitcambridge r?
> Remove sendClose logging and unnecessary verifyNuke.

- autopush/endpoint.py
- autopush/router/simple.py
- autopush/router/webpush.py
- autopush/settings.py
- autopush/tests/test_endpoint.py
I realized we don't need a separate message ID; we can just use the encrypted token as the DynamoDB hash key. Since each token uses a 128-bit IV, it's as unique as a UUID. We still decrypt and verify the token to extract the UAID and channel ID; we just use the original, encrypted form as the message ID.
This is particularly helpful for receipts, where we need to send push promises containing the message URL. By reusing the token as the message ID (and version), we avoid having to store and pass around the URL. It also makes for shorter message URLs, and drops `prepare_notification`—which I didn't really like.
@bbangert, @jrconlin r?
> Use the message token as the message ID

- CHANGELOG.rst
- autopush/main.py
- autopush/tests/test_integration.py
- autopush/tests/test_websocket.py
- autopush/websocket.py
- docs/api/websocket.rst
Nice, trivial change. Closes #117.
@bbangert r?
> Rename `SimplePushServerProtocol` to `PushServerProtocol`

- .travis.yml
- README.rst
- docs/index.rst
Coveralls hasn't been happy for a while. The Esprima folks seem to like Codecov; let's give it a try.
> Use Codecov for code coverage

- CHANGELOG.rst
- autopush/db.py
- autopush/tests/test_websocket.py
- autopush/websocket.py
If an existing client opts in to data delivery via the `use_webpush` flag, we should reset its ID so that its existing subscriptions are invalidated. (It's possible for the client to keep track of this, too; I just thought it would be cleaner for the server to handle it, since we already store the router type).
@bbangert, @jrconlin r?
> Reset UAIDs for clients that change their router type

- CHANGELOG.rst
- autopush/endpoint.py
- autopush/tests/test_endpoint.py
- autopush/tests/test_integration.py
Another quick win...
* Use 413 for messages that exceed the maximum size, per the [Web Push draft](https://unicorn-wg.github.io/webpush-protocol/#send).
* Use 404 for invalid tokens, and 400 for missing encryption headers. 401 signals invalid credentials, and [RFC 7235](https://tools.ietf.org/html/rfc7235#section-3.1) mandates a `WWW-Authenticate` response header. Neither is really applicable here. :bike: :house: :art:
@bbangert r?
> Clarify endpoint response status codes

- autopush/db.py
- autopush/tests/test_integration.py
Fixes an uncaught `TypeError` in production.
@jrconlin r?
> Ensure `all_channels` always returns an empty set

- CHANGELOG.rst
- autopush/main.py
- autopush/settings.py
- autopush/tests/test_websocket.py
- autopush/websocket.py
In order for the clients to identify which service they are dealing with, provide the running environment in json responses. Being aware of the environment will help in debugging issues with applications.
This patch may need more tests. I tested it out with simplepush_test locally and added a basic test case.
Ref: #50
> [WIP] Provide the service enviornment information

- CHANGELOG.rst
- autopush/db.py
- autopush/endpoint.py
- autopush/logging.py
- autopush/main.py
- autopush/router/apnsrouter.py
- autopush/router/gcm.py
- autopush/router/interface.py
- autopush/router/simple.py
- autopush/router/webpush.py
- autopush/senderids.py
- autopush/settings.py
- autopush/tests/test_endpoint.py
- autopush/tests/test_main.py
- autopush/tests/test_router.py
- autopush/tests/test_senderids.py
- autopush/utils.py
- autopush/websocket.py
- docs/api/senderids.rst
Randomly select a GCM senderid from a list stored in an S3 bucket and include it with the initial registration request. This was proposed by the client team as a way to allow for GCM SenderIDs to be rotated in case an ID is disqualified for any reason. 
In addition, if the client doesn't include a ChannelID in the incoming registration request, there's no reason why we can't generate and return one on the server. This simplifies things on the client.
Since the GCM router requires modifying the registration response, it was decided that all routers should be given that option.
@bbangert r?
> Add server generated SenderIDs and ChannelIDs for GCM clients

- CHANGELOG.rst
- autopush/main.py
- autopush/tests/test_main.py
- autopush/utils.py
ConfigArgParse has a serious issue with
foo=True
it wants a flag to simply exist or not to indicate value.
* Remove str2bool processing
* Changed default behavior to always enable CORS for endpoints
_**NOTE: THIS WILL REQUIRE MODIFICATION OF THE PUPPET DEPLOYMENT SCRIPT**_
resolves #205 
@bbangert r?
> Convert arg handlers to ConfigArgParse std.

- .editorconfig
- CHANGELOG.rst
> chore: Add .editorconfig for consistent styling across editors.

- CHANGELOG.rst
- autopush/endpoint.py
- autopush/logging.py
- autopush/main.py
- autopush/router/gcm.py
- autopush/senderids.py
- autopush/settings.py
- autopush/tests/test_endpoint.py
- autopush/tests/test_logging.py
- autopush/tests/test_main.py
- autopush/tests/test_router.py
- autopush/tests/test_senderids.py
- docs/api/senderids.rst
- docs/api/utils.rst
Resolves #220 
In addition, the following were added to help GCM debugging:
Added the flags:
--gcm_enabled - Enable GCM bridge
--s3_bucket=None - will skip using remote S3 (to resolve issues with moto)
--human_logs - Render stdout logs in a more human readable format
Removed the flags:
--gcm_apikey
* Changed the format of the SenderID list
* Updated the docs to fix errors and reflect new state.
@bbangert r?
> Add Auth token handling for Sender IDs

- CHANGELOG.rst
- autopush/db.py
- autopush/endpoint.py
- autopush/router/apnsrouter.py
- autopush/tests/test_db.py
- autopush/tests/test_endpoint.py
- autopush/tests/test_main.py
- autopush/tests/test_router.py
- autopush/utils.py
- docs/api/senderids.rst
- requirements.txt
- test-requirements.txt
* Converted proprietary AUTH to HAWK for client REST calls.  Closes #201.
* Added DELETE function to client REST interface. Closes #183 
* Fixes for doc typo
* fixes to CHANGELOG to point to correct S3 repo
* increased test coverage for db to compensate for removed AUTH testing.
@bbangert r?
> Add HAWK and DELETE to client REST interfaces

- CHANGELOG.rst
- autopush/db.py
- autopush/main.py
- autopush/router/simple.py
- autopush/router/webpush.py
- autopush/settings.py
- autopush/tests/test_db.py
- autopush/tests/test_endpoint.py
- autopush/tests/test_integration.py
- autopush/tests/test_main.py
- autopush/tests/test_router.py
- autopush/tests/test_websocket.py
- autopush/websocket.py
- docs/architecture.rst
This PR add's message table rotation for webpush users, and retains a current_month attribute in the router table for the user indicating which message table to use for notifications.
Table rotation occurs when a client connects, after it has ack'd all remaining notifications in the table it was last on. Then the channels entry is copied over, and the current_month updated.
Webpush users with an account prior to table rotation will have their UAID reset so they can re-register channels properly with the table rotation scheme.
Closes #191.
@jrconlin r?
> Add message table rotation for webpush users

- autopush/db.py
- autopush/endpoint.py
- autopush/tests/test_db.py
- autopush/tests/test_endpoint.py
Checked over the delete code to ensure that proper states and errors are
being returned. Added tests to better guard against changes.
* Removed "all" flag for delete_message
* check state where possible and without increasing read costs.
@bbangert r?
> bug: Fix delete error reporting. resolves bugzilla:1215253

- CHANGELOG.rst
- autopush/db.py
- autopush/endpoint.py
- autopush/settings.py
- autopush/tests/test_db.py
- autopush/tests/test_endpoint.py
- autopush/tests/test_integration.py
- autopush/tests/test_main.py
- autopush/websocket.py
Utilizes the existing router last_connect global index to track the first
connect of the month for the client. The last_connect number is a number
joining the year/month/hour with a random int to reduce hot key contention
on the index.
Additional integration tests were added to verify the last_connect is updated
appropriately for simplepush and webpush clients.
This changes the get_rotating_message_table function to automatically create
the table if needed, reducing boiler-plate in the settings object wrapping
that behavior.
Registration endpoint handlers saving router data all update the last_connect
as well (new channels do not update the value).
Closes #253
@jrconlin r?
> feat: track last month connected using last_connect router field

- CHANGELOG.rst
- autopush/main.py
- autopush/router/gcm.py
- autopush/tests/test_main.py
- autopush/tests/test_router.py
- docs/http.rst
* Fixes #289
* Throws 413 error if the encoded, outbound message is more than
max_data (this should prevent unexpected developer confusion if the
bridge rejects a block that is nearly max_data length.)
* Added note to docs.
@bbangert r?
> Convert the outbound encrypted GCM data to base64

- CHANGELOG.rst
- autopush/endpoint.py
- autopush/tests/test_endpoint.py
- autopush/tests/test_websocket.py
- autopush/websocket.py
* Added for websocket and Registration handlers
* Note: Websocket adds a slightly different format.
"protocol:ip:socket" (e.g. "tcp4:1.2.3.4:1234") I'm not
sure how ipv6 is registered ("tcp6:[1:2:3:4]:1.2.3.4"?) so not
quite sure how or if I should trim it down.
Fixes: #292
@bbangert r?
> Add remote-host to base metrics tags

- CHANGELOG.rst
- autopush/db.py
- autopush/endpoint.py
- autopush/router/apnsrouter.py
- autopush/router/gcm.py
- autopush/router/interface.py
- autopush/router/simple.py
- autopush/router/webpush.py
- autopush/senderids.py
- autopush/tests/test_db.py
- autopush/tests/test_endpoint.py
- autopush/tests/test_router.py
- autopush/tests/test_senderids.py
- autopush/tests/test_websocket.py
- autopush/websocket.py
- test-requirements.txt
* pass "router_token" for senderid lookup
* Clean up comments to be more clear about what each token is.
* Add ability for clients to request "dry run"
* better exam of gcm data response block.
* fix test SenderID hash to match reality.
@bbangert r?
>  Fix GCM data block send. Fixes #297

- CHANGELOG.rst
- autopush/__init__.py
- autopush/tests/test_integration.py
- autopush/tests/test_websocket.py
- autopush/websocket.py
This fixes the multiple write issue for new webpush and simplepush users by
updating the previous value the way moto does (incorrectly in moto's case).
Fixes #300, again.
> bug: fix the multiple write issue for new webpush users

- CHANGELOG.rst
- autopush/endpoint.py
- autopush/router/interface.py
- autopush/router/webpush.py
- autopush/tests/test_endpoint.py
This tags the router responses with additional information for webpush calls
so that our logging statements can determine the three cases under which we
return a 201: delivered, stored, dropped due to TTL 0.
Fixes #315 
@jrconlin r?
> feat: tag webpush notifications for more thorough logging

- CHANGELOG.rst
- autopush/__init__.py
- autopush/main.py
This add's the looping task that the connection nodes have that ensures
the table objects for this months message table are available for use.
Fixes #319 
@jrconlin r?
> bug: ensure message table objects for current month are available

- CHANGELOG.rst
- autopush/db.py
- autopush/tests/test_integration.py
During monthly rotation, if a user drops the connection after the monthly
rotation has begun, but before it completed, then the message table will be
updated but not the router table. This means that the next call will fail
since put_item wasn't called with overwrite=True. This patch fixes that
and includes an integration test to verify the fix.
Closes #320
@jrconlin r?
> bug: overwrite records during monthly migration to avoid disconnect edge-case

- CHANGELOG.rst
- autopush/endpoint.py
- autopush/router/simple.py
- autopush/tests/test_endpoint.py
- autopush/tests/test_integration.py
- autopush/tests/test_router.py
- docs/http.rst
Previously 404 was returned for multiple classes of errors when the endpoints
would never in fact be good, so a 410 is appropriate. In one case a 404 was
returned instead of a 400 which properly addresses the fact that the URL was
not validly constructed.
Closes #312 
@jrconlin r?
> bug: use appropriate 400, 410 instead of 404 for permanent errors

- CHANGELOG.rst
- autopush/endpoint.py
- autopush/tests/test_endpoint.py
- autopush/tests/test_websocket.py
- autopush/websocket.py
Log all notification ack's for simplepush/webpush, along with the router
key, message/channel ids, and uaid hash. Update logging on autoendpoint
to match format and keys for correlation.
Closes #331 
@jrconlin r?
> feat: log notification acks

- CONTRIBUTING.md
This document was originally based on the angular.js work and thus
has a fair bit of dependency on angular style knowledge. Adding
examples and proper deep links makes the document easier to
understand for new-comers.
@bbangert r?
> docs: update CONTRIBUTING.md doc to match our style

- autopush/router/webpush.py
- autopush/tests/test_endpoint.py
- autopush/tests/test_router.py
> bug: include crypto-key when routing & storing messages

- autopush/endpoint.py
- autopush/router/webpush.py
- autopush/tests/test_endpoint.py
- autopush/tests/test_integration.py
- docs/http.rst
Allows webpush notifications with no TTL header included as long
as the client is online. Otherwise a 400 is returned with a
descriptive URL including a link to the appropriate docs on how to
include a proper TTL.
Refactors how the TTL setup code is handled, and cleans up the 400
logging for consistency.
Closes #357, #358
@jrconlin r?
> fix: allow webpush w/no ttl & cleanup 400 logging

- autopush/logging.py
- autopush/tests/test_logging.py
- requirements.txt
- test-requirements.txt
Update the requirements to use the latest autobahn, and the recent
twisted/txaio/raven/eliot as well. Minor fixes to logging to ensure
the log output works with the new keys twisted 15.5 introduced.
Closes #351, #180 
@jrconlin r?
> feat: upgrade autobahn/twisted to 0.12/15.5

- autopush/endpoint.py
- autopush/router/webpush.py
- autopush/tests/test_endpoint.py
Missing TTL headers are being logged resulting in high levels of noise
in the Sentry logs. Set the "log_exception" param to False to prevent
the message from going to the system log.
issue #366
@bbangert r?
> bug: silence missing TTL errors from sentry log

- autopush/router/webpush.py
- autopush/tests/test_integration.py
- autopush/tests/test_router.py
#361 was a bit too aggressive. Firefox expects `Crypto-Key` and `Encryption-Key` to be converted to `crypto_key` and `encryption_key`.
This should be part of tomorrow's deploy.
@jrconlin r?
> bug: Normalize encryption headers

- autopush/endpoint.py
- autopush/router/gcm.py
- autopush/tests/test_router.py
- configs/autopush_endpoint.ini
The code was previously using the configuration option of gcm_ttl
instead of the user supplied TTL. Instead, use gcm_ttl as the minimum
TTL in case of message loss due to TTL 0.
closes #374 
@bbangert
> bug: pass TTL Header value to GCM

- autopush/logging.py
- autopush/tests/test_websocket.py
- autopush/websocket.py
Logging considers "message_type" to be a reserved term. This causes us
to lose some logging information.
@bbangert r?
> bug: change message_type to message_source

- autopush/db.py
- autopush/endpoint.py
- autopush/logging.py
- autopush/main.py
- autopush/router/webpush.py
- autopush/settings.py
- autopush/tests/test_db.py
- autopush/tests/test_endpoint.py
- autopush/tests/test_integration.py
- autopush/tests/test_websocket.py
- autopush/websocket.py
Channels can include a public key when registering a new subscription
channel. This public key should match the public key used to send
subscription updates later.
NOTE: this patch changes the format of the endpoint URLs, & the content
of the endpoint URL token. This change also requires that ChannelIDs be
normalized to dashed format, (e.g. a lower case, dash delimited string
"deadbeef-0000-0000-deca-fbad11112222") This is the default mechanism
used by Firefox for UUID generation. It is STRONGLY urged that clients
normalize UUIDs used for ChannelIDs and User Agent IDs. While this
should not break existing clients, additional testing may be required.
Closes #326
@bbangert r?
> feature: allow channels to register with public key

- autopush/router/webpush.py
The client expects all header values transmitted to be lower case with
underbars. (e.g."Encryption-Key" would become "encryption-key") The
current code enforces this rule for the header data that is included
as part of the WebPush update.
Closes #373 
@bbangert
> bug: force header values to lowercase underscored values

- autopush/router/simple.py
- autopush/tests/test_router.py
When a user is not connected, store the message and do not return a 503.
Closes #378 
@bbangert r?
> bug: don't return 503 for disconnected user

- autopush/logging.py
- autopush/tests/test_logging.py
Deadlocks due to raven reporting can occur when exceptions
are logged during GC, as twisted may do. As such, the raven
call should be sent to the event loop so that twisted's
__del__ call can return uninterrupted.
Closes #387 
@jrconlin r?
> fix: send raven calls to event loop

- autopush/tests/test_websocket.py
- autopush/websocket.py
Empty pending notification arrays may be returned. Removing a value can
trigger a ValueError that can be safely ignored.
Closes #385 
@bbangert r?
> bug: capture ValueError for empty notifications arrays

- autopush/endpoint.py
- autopush/tests/test_endpoint.py
Also remove raw token from jwt logging, it's redundant.
Closes #389
@bbangert r?
> feature: log TTL into client_info as 'message_ttl'

- autopush/db.py
- autopush/tests/test_db.py
Records containing only a UAID are corrupt. Drop these records and
return a 410 to the server.
Closes #400 
@bbangert r?
> bug: Clear corrupted router records

- autopush/settings.py
- autopush/tests/test_endpoint.py
Changes v0 token validation from simple check containing a : into
regex expecting valid uuid characters on either side of the : as
well.
Closes #406 
@jrconlin r?
> feat: validate v0 tokens more thoroughly

- autopush/crypto_key.py
- autopush/endpoint.py
- autopush/settings.py
- autopush/tests/test_cryptokey.py
- autopush/tests/test_endpoint.py
- autopush/utils.py
The Crypto-Key header has a different format than what was first
understood. A valid Crypto-Key header may look like `keyid="foo";
key1="data",key2="data"`. This patch specialized Crypto-Key parsing
to a class.
Closes #410
@bbangert r?
*Note*: I'd love to have a full integration test where we can check that the VAPID data was recorded correctly, as well as the data passed through. test_integration's TestWebpush.test_basic_delivery_with_vapid contains most of what would be required, but I don't know how to get the _client_info to check that the JWT content matches what we're expecting.
> bug: decode and process crypto-key header correctly

- .dockerignore
- .travis.yml
- Dockerfile
- Makefile
- requirements.txt
- test-requirements.txt
Dockerfile and Makefile were both broken. This fixes the Dockerfile
and uses the latest PyPy 5.0 for building the container.
Closes #414 
@jrconlin r?
> fix: fix dockerfile for automated builds

- .travis.yml
- autopush/db.py
- autopush/endpoint.py
- autopush/health.py
- autopush/logging.py
- autopush/main.py
- autopush/router/apnsrouter.py
- autopush/router/gcm.py
- autopush/router/simple.py
- autopush/senderids.py
- autopush/tests/test_endpoint.py
- autopush/tests/test_health.py
- autopush/tests/test_integration.py
- autopush/tests/test_logging.py
- autopush/tests/test_router.py
- autopush/tests/test_websocket.py
- autopush/utils.py
- autopush/websocket.py
- doc-requirements.txt
- requirements.txt
- test-requirements.txt
Updates all logging calls to use the newer logging utilities in
twisted. This obsoletes the use of eliot, as twisteds logger can
handle arbitrary keywords. The logging handling has been revamped
into a more easily testable class that implements twisteds IObserver
for easy logger observing.
log_level support has been re-added so that calls can be appropriately
scoped by logging type. Existing info/msg log calls now use appropriate
log levels, with delayed function calls to prevent unnecessary overhead
when formatting objects if the log message is ignored.
Closes #419 
@jrconlin r?
> feat: update logging for newstyle twisted and file output

- .travis.yml
- autopush/logging.py
- autopush/main.py
- autopush/tests/test_logging.py
- requirements.txt
- test-requirements.txt
Add's a component to the logger that optionally dumps the log output
directly to AWS Firehose. Logging should be set to 'json' for proper
reading.
Closes #421 
@jrconlin r?
> feat: allow logging to batch send to aws firehose

- autopush/endpoint.py
- autopush/tests/test_endpoint.py
Two things: 
1) fail.value.message can sometimes return a class, which will cause the logging to break.
2) Be a lot more rigorous about padding tests. There are some values that all the padding in the world will fail to decode, but we should be certain that only those actually fail.
@bbangert r?
> bug: enforce fail.value.message to string

- autopush/tests/test_cryptokey.py
A different order of keys is making the push service fail for me with 500 (Internal Server Error), so I wanted to try this test to make sure the CryptoKey parsing is working correctly.
I haven't run the tests locally, I'm not sure how to build and run tests.
> Test a different order of keys in Crypto-Key

- autopush/db.py
- autopush/settings.py
- autopush/tests/test_db.py
- autopush/tests/test_main.py
- autopush/tests/test_websocket.py
- autopush/websocket.py
A user that tries to connect from a period longer than we currently
allow for could cause a "KeyError" on the server. Instead, we should
require that the user use a new UAID, which shoud cause the client to
re-register older connections.
Closes #350 
@bbangert r?
> bug: limit valid months to acceptable range

- requirements.txt
- test-requirements.txt
A cffi dependency pinning was missed because test-requirements was
not matching requirements.txt. This caused build issues for ops.
> fix: update cffi dep and ensure test reqs matches reqs

- autopush/endpoint.py
- autopush/tests/test_endpoint.py
Logging does not handle object exports well. Flattening JWT by prefixing
"jwt_" to the names of values to prevent potential conflicts
@bbangert r?.
> bug: flatten JWT for logging.

- autopush/endpoint.py
- autopush/router/apnsrouter.py
- autopush/router/gcm.py
- autopush/tests/test_endpoint.py
- autopush/tests/test_router.py
I cleaned this up a bit, since we already validate the headers and encode the payload in `EndpointHandler`. While I was here, I also updated the APNs router to forward the crypto headers (even though we don't have any active consumers at the moment).
@jrconlin r?
> refactor: Remove duplicate validation logic in the GCM and APNs routers

- autopush/endpoint.py
- autopush/settings.py
- autopush/tests/test_endpoint.py
- autopush/tests/test_integration.py
- autopush/tests/test_router.py
- autopush/tests/test_websocket.py
- autopush/utils.py
For restricted subscriptions with an app server key, we include the SHA-256 hash of the *encoded* form in the endpoint URL. This can be a problem if one side uses padded input, and the other uses unpadded. Another complication is, while RFC 7515 forbids padding, Python's Base64 decoder requires it. As we discussed on IRC a few days ago, keeping track of these different forms is error-prone.
This PR adds two helper functions to encode and decode unpadded Base64. It also normalizes VAPID keys to the unpadded form, regardless of whether the sender included padding.
Finally, I noticed `self.assertRaises` can silence failures, so I switched to using Nose's `assert_raises` instead.
@bbangert r?
> fix: Canonicalize Base64 URL-encoded values per RFC 7515

- autopush/endpoint.py
- autopush/tests/test_endpoint.py
I think an optional `key` field in the body is all that's needed. Closes #423.
@jrconlin r?
> feat: Support app server keys via the HTTP interface

- autopush/tests/test_websocket.py
- autopush/websocket.py
- docs/architecture.rst
- docs/http.rst
- docs/style.rst
The code normalizes UUIDs used for channelIDs and UIADs to lower case,
dashed format. The docs now state that and the code will reject UUIDs
that are not well formatted. This is important for clients that may
normalize differently.
BREAKING CHANGE: This patch will reject UUIDs that are not expressed as
lower case, dash formatted (e.g. "00001111-aaaa-bbbb-cccc-222233334444")
Closes #392
@bbangert , @kitcambridge r?
> fix: Correct documents to strongly recommend well formatted UUIDs

- autopush/db.py
- autopush/main.py
- autopush/settings.py
- autopush/tests/test_db.py
Preflight would create new accounts which could throw off metrics.
This patch solves this in two ways; It uses static UAIDs matching
"deadbeef00000000deadbeef\d{8}" and deletes the created data once
the preflight is done.
Closes #434 
@bbangert r?
> bug: Use static UAIDs for preflight, clean up after.

- autopush/endpoint.py
- autopush/tests/test_endpoint.py
The client will soon reject any key content that includes padding.
The server will need to watch and strip it. We should also return a
warning message, however the likelihood of that warning being noticed
is minimal.
Closes #451 
@bbangert, @kitcambridge r?
(Let the great debate ensue!)
> bug: Strip padding from key content

- autopush/endpoint.py
> bug: Log status_code & errno for all errors

- requirements.txt
- test-requirements.txt
gnureadline is still maintained while readline has fallen behind and
has compile errors on some platforms.
@jrconlin r?
> feat: use gnureadline instead of readline

- autopush/settings.py
- autopush/tests/test_endpoint.py
- autopush/tests/test_integration.py
- autopush/utils.py
Since fernet passes it's content through base64 handling, it's just as
picky about padding as other base64 instances. For now, strip padding
from outbound endpoints and reapply it (if needed) to inbound endpoints.
Closes #466 
@bbangert r?
> bug: Normalize padding handling for restricted subscriptions

- autopush/endpoint.py
- autopush/main.py
- autopush/router/gcm.py
- autopush/tests/test_endpoint.py
- autopush/tests/test_main.py
- docs/api/endpoint.rst
- docs/http.rst
Bridged devices do not use the websocket connection, so NAKs can be
lost. Our system generally ACKs messages when they're handed off to the
bridge system, but clients can 'retro-actively' NAK a packet.
Since connections should be limited to the minimum possible, and NAKs
are (hopefully) more rare and meaningful than ACKs, only need to log
NAKs.
Also fix up missing coverage for bad senderid JSON.
Closes #469
@bbangert r?
> feat: Log naks from bridged connections via REST API

- autopush/noseplugin.py
Only during debugging sessinos does a full object summary of each
track statement assist. As such, by default only the deltas are
now shown in the summary.
@jrconlin r?
> chore: shorten delta output to just delta lines

- CONTRIBUTING.md
- README.md
- docs/install.rst
As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.
> Convert readthedocs links for their .org -> .io migration for hosted projects

- autopush/exceptions.py
- autopush/settings.py
- autopush/tests/test_endpoint.py
- autopush/tests/test_integration.py
- autopush/tests/test_web_validation.py
- autopush/tests/test_websocket.py
- autopush/web/base.py
- autopush/web/simplepush.py
- autopush/web/validation.py
- autopush/web/webpush.py
- test-requirements.txt
This refactor splits out the webpush endpoint to a new URL path
and uses the marshmallow schema to validate requests.
The webpush endpoints are issued under a new URL endpoint to
avoid conflicts with the existing.
Closes #379 
@jrconlin r?
> feat: refactor webpush endpoint for validation schemas

- autopush/router/apnsrouter.py
- autopush/router/gcm.py
- autopush/tests/test_router.py
This adds metric calls for attempted and successful bridge sends.
format:
updates.client.bridge.[apns|gcm].[attempted|succeeded]
Errors are already logged.
closes #497
@bbangert r?
> feat: add metrics to bridge protocols

- autopush/diagnostic_cli.py
- autopush/main.py
- autopush/tests/test_diagnostic_cli.py
- autopush/tests/test_main.py
Parse-args can aggressively pull local config files. Tests are set to
exclude local files, but recent file changes added the shared_config
files back in causing local unit tests to fail.
Closes #515 
@bbangert r?
> bug: remove shared file inclusion for tests

- autopush/endpoint.py
Previously, several error classes were not logged as they were debug
level, not info level. This fix remedies that.
Closes #518 
@jrconlin r?
> fix: log message errors as info instead of debug

- autopush/tests/test_db.py
- autopush/tests/test_endpoint.py
- autopush/tests/test_web_webpush.py
- autopush/tests/test_websocket.py
- autopush/utils.py
Older UAIDs contain invalid characters and should be rejected.
Closes #519 
@bbangert r?
> bug: Invalidate UAIDs that are not lowercase or contain dashes

- autopush/db.py
- autopush/tests/test_websocket.py
- autopush/websocket.py
When a client says hello, the register user method now performs a router lookup
to verify the record actually exists and has the appropriate necessary attributes.
A check is also done for webpush users to verify the server still has a table object
it can use to pull notifications for during verification so the uaid can be reset if
needed.
This cleans up the hello handling, removing the need for a separate hello finish
and simplifying  the callbacks.
Closes #523 
@jrconlin r?
> fix: refactor register uaid lookup to verify proper records

- autopush/tests/test_websocket.py
- autopush/websocket.py
It was possible previously for a corrupted record to be missing a router_type
which caused AWS ValidationError's. This change ensures all records have
a router_type and connected_at which are required values for the register
user expression condition that AWS checks.
Closes #526 
@jrconlin r?
> fix: ensure router_type is present in all records

- autopush/tests/test_db.py
- autopush/tests/test_websocket.py
moto's testing harness is a bit buggy, it was returning errors in
a semi-random manner during test-runs and failing to do
validation checks that DynamoDB performs. As such we now
spin up the Java DynamoDB local server for these test files to
ensure consistent responses.
Closes #531 
@jrconlin r?
> fix: remove use of buggy moto from websocket/db tests

- autopush/db.py
- autopush/endpoint.py
- autopush/router/gcm.py
- autopush/tests/test_db.py
- autopush/tests/test_endpoint.py
- autopush/tests/test_websocket.py
AWS throws an exception if conditional args are not defined, this
impacted tests by failing, but throwing an exception and causing fun
havoc. register_user now fails if all conditionals are not met
(preserving previous behaviors). Added tests for older records that may
be incomplete.
Some formatting fixes included as well
@bbangert r?
> bug: fix up AWS conditional binding and assoc. conditions

- autopush/tests/test_web_validation.py
- autopush/web/validation.py
> fix: catch InvalidToken exceptions from fernet

- autopush/db.py
- autopush/tests/test_db.py
DynamoDB throws a condition check failure if you put_item and
it already exists. This can occur when we save a message that
may already exist when a user hops servers without ack'ing. We
should allow it since it consumes the same resources.
Closes #535 
@jrconlin r?
> fix: overwrite existing messages instead of throwing an error

- autopush/exceptions.py
- autopush/router/interface.py
- autopush/settings.py
> fix: kill mutable default arguments

- autopush/main.py
- autopush/router/__init__.py
- autopush/router/fcm.py
- autopush/tests/test_main.py
- autopush/tests/test_router.py
- configs/autopush_shared.ini
- docs/api.rst
- docs/api/router/fcm.rst
- docs/http.rst
- docs/install.rst
Adds 'fcm' as a client selectable router, to allow 'gcm' to persist or
act as a fallback.
closes #517 
@bbangert r?
> feat: Add FCM router support

- autopush/endpoint.py
- autopush/tests/test_endpoint.py
- autopush/tests/test_web_base.py
- autopush/web/base.py
OPTIONS and HEAD requests are made by XHTTP and fetch calls in browsers.
These need to have tests that closely parallel the arguments being
generated in URL parsers in main.py.
closes #551 
@bbangert r?
> bug: Handle URL arguments to OPTIONS and HEAD requests

- autopush/tests/test_utils.py
- autopush/tests/test_websocket.py
- autopush/utils.py
- autopush/websocket.py
- pypy-requirements.txt
- requirements.txt
- test-requirements.txt
The user-agent string is now parsed and normalized to fewer values for DataDog. The
raw parsed version is also included in all websocket.py logging statements for easier
filtering in our logging. Existing raw user_agent string will remain so that existing log
parsing systems using it can function as normal.
Closes #487 
@jrconlin, @pjenvey r?
> feat: normalize user-agent for datadog and parse for raw logging

- autopush/diagnostic_cli.py
- autopush/endpoint.py
- autopush/router/gcm.py
- autopush/tests/test_endpoint.py
- autopush/tests/test_router.py
- autopush/tests/test_web_validation.py
- autopush/web/base.py
- autopush/web/validation.py
- autopush/web/webpush.py
Adds logic to fail endpoints with invalid SenderIDs so that they fail fast on
post. Reduced logging level of GCM SenderID errors, since there's going
to be a lot of those for a while.
Closes #556 
@bbangert @pjenvey r?
> Bug: Fix webpush to reject endpoints which have an invalid GCM senderid

- autopush/endpoint.py
- autopush/router/simple.py
- autopush/router/webpush.py
- autopush/web/validation.py
Avoids the uaid error on fetch in the preflight by re-using the existing fetched
data. If the current_month doesn't exist, this is an invalid record so the uaid
is removed as it should've been.
closes #542, #553 
@jrconlin, @pjenvey r?
> fix: avoid uaid error in webpush preflight

- autopush/router/gcm.py
Return the GCM data overflow error to the subscription server, but
there's no need to record it into Sentry.
Closes #552 
@bbangert , @pjenvey r?
> bug: Do not record the GCM data overflow error

- autopush/endpoint.py
- autopush/router/fcm.py
- autopush/router/simple.py
- autopush/router/webpush.py
- autopush/tests/test_web_validation.py
- autopush/web/validation.py
A bad or improperly formatted VAPID object may generate a ValueError.
While important, and notable to the originator, this does not need to go
into Sentry.
Also fixes some logging formatting errors
closes #562 
> bug: Add ValueError trap for extract_jwt

- autopush/router/fcm.py
- autopush/tests/test_router.py
Closes #556 
(picks up spare from https://github.com/mozilla-services/autopush/pull/561)
@bbangert @pjenvey r?
> bug: Fix up FCM library to reject enpdoints with invalid FCM senderids

- docs/index.rst
Was this move documented somewhere? updates-autopush-dev.stage.mozaws.net doesn't resolve anymore.
URLs from this page work https://wiki.mozilla.org/QA/Push_Notifications
> Update dev endpoint

- autopush/db.py
- autopush/tests/test_web_webpush.py
- autopush/web/webpush.py
Webpush web handler should not remove router_type from UAID information.
Also fixed error message formatting and added appropriate test to ensure
that router_type persists.
closes #549 
> bug: Do not remove router_type from UAID info

- autopush/router/fcm.py
- autopush/tests/test_router.py
- doc-requirements.txt
- pypy-requirements.txt
- requirements.txt
- test-requirements.txt
FCM, while compatible with GCM, has a much richer error handler. We
should also use a fcm specific bridging library.
closes #589 
@pjenvey r?
> bug: Update FCM handler to more accurately reflect API

- autopush/endpoint.py
- autopush/tests/test_endpoint.py
- autopush/tests/test_web_base.py
- autopush/tests/test_web_validation.py
- autopush/web/validation.py
- docs/http.rst
VAPID spec recently changed to specify "WebPush" as valid Authorization
token ID. Code allows either Bearer or WebPush while external code
transitions.
Closes #592 
@pjenvey, @kitcambridge r?
> feat: Allow both "Bearer" and "WebPush" as Auth tokens

- autopush/endpoint.py
- autopush/tests/test_endpoint.py
- autopush/tests/test_integration.py
- autopush/tests/test_web_validation.py
- autopush/web/validation.py
Check the encryption headers to make sure they're roughly valid before
passing them on to the client.
Closes #456
@pjenvey r?
>  feat: Validate Encryption/C-Key headers in preflight

- autopush/main.py
- autopush/tests/test_limitedhttpconnection.py
- autopush/web/limitedhttpconnection.py
Limits the amount of data preventing a potential DDoS. This extends much
of what's already in place. Twisted limits TCP read chunks to 65K. It
also already limits the max length of header lines to 16,384 bytes. This
forces connections closed if too much data is attempted to be sent.
NOTE: currently too much data events are not being logged, mostly due
to the fact that errors would lack a good deal useful info.
@pjenvey r?
> feat: Limit the size of allowed HTTP bodies & headers

- autopush/metrics.py
- autopush/settings.py
- autopush/tests/test_integration.py
- autopush/tests/test_metrics.py
- autopush/web/validation.py
- docs/http.rst
URL's that are invalid should return a 404, just like any other
invalid URL.
Closes #578
> fix: return 404 for invalid URL's for consistency

- autopush/router/fcm.py
- autopush/router/gcm.py
- autopush/tests/test_router.py
Since this value is hard coded by Google, we can hard code it into
our bridge.
closes #615
> bug: limit max TTL for GCM/FCM

- autopush/tests/test_websocket.py
- autopush/websocket.py
Closes #606 
r? @pjenvey @jrconlin
> fix: trap UnicodeEncodeError

- autopush/router/simple.py
- autopush/websocket.py
* prefer base classes ConnectError/ConnectionClosed/ResponseFailed,
covering ConnectionRefused/UserError, ConnectionLost/Done,
ResponseNeverReceived
* handle ResponseFailed (ResponseNeverReceived) in the routers as
a broken connection
* trap these in PushServerProtocol._notify_node
closes #613, #554
r? @bbangert @jrconlin
> fix: handle more errors to connection nodes

- autopush/router/simple.py
- autopush/tests/test_router.py
- doc-requirements.txt
- pypy-requirements.txt
- requirements.txt
- test-requirements.txt
closes #623 
r? @jrconlin @bbangert
> fix: kill dead_cache, it's no longer used

- autopush/crypto_key.py
- autopush/db.py
- autopush/diagnostic_cli.py
- autopush/endpoint.py
- autopush/health.py
- autopush/log_check.py
- autopush/logging.py
- autopush/main.py
- autopush/router/simple.py
- autopush/settings.py
- autopush/tests/test_db.py
- autopush/tests/test_endpoint.py
- autopush/tests/test_health.py
- autopush/tests/test_logging.py
- autopush/tests/test_main.py
- autopush/tests/test_router.py
- autopush/tests/test_web_base.py
- autopush/tests/test_web_validation.py
- autopush/tests/test_websocket.py
- autopush/utils.py
- autopush/web/validation.py
* replaces python reserved word var names
* replaces mixed case var names
* fixes setting chain breaks (message_read/write_throughput)
* removes unneeded var instantiations
* normalize HealthHandler to base from AutoendpointHandler, so
ap_settings is known
* instantiate from dict() rather than {}
* limit except handlers to known exceptions
issue #612
> feat: Code cleanup

- autopush/router/gcm.py
- autopush/router/webpush.py
Some info that needs to be logged is not JSON serializable. Use repr()
for now.
closes #631 
@bbangert @pjenvey r?
> bug: do not try to JSON serialize log output

- autopush/base.py
- autopush/endpoint.py
- autopush/log_check.py
- autopush/logging.py
- autopush/tests/test_logging.py
- autopush/tests/test_web_base.py
- autopush/tests/test_web_webpush.py
- autopush/web/base.py
- autopush/web/simplepush.py
- autopush/web/validation.py
- autopush/web/webpush.py
* when calling drop_user and the response.router_data is empty, fetch
the current UAID from known uaid_data
* make the logging far more verbose by adding _client_info to raven
calls
closes #629
@bbangert @pjenvey r?
> bug: provide better logging and fix UAID misreference

- autopush/crypto_key.py
- autopush/endpoint.py
- autopush/settings.py
- autopush/tests/test_endpoint.py
- autopush/web/validation.py
closes #646 
Also took the opportunity to fix the `(tuple) = function()` returns. 
> bug: Require auth header for endpoints with v2

- .travis.yml
quickest solution is to install virtualenv on its system python, so we
avoid the old virtualenv it has
travis sets up a virtualenv for us so our use of virtualenv here is redundant, at some point in the future we should probably stop doing it. I think we can use some of its caching features for pip/dynamodb too..
> chore: fix travis' virtualenv giving us an older python

- autopush/tests/__init__.py
- autopush/tests/test_router.py
- autopush/tests/test_websocket.py
- autopush/websocket.py
Several db operations from websocket clients now handle provisioned exceeded
errors more gracefully. Register now returns an error message about the overload
so that a client may retry. During the initial notification check, if an error occurs the
notification check is re-scheduled to occur at a later time. Finally, if the provision
error hits during the monthly change-over, the client remains connected and the
migration is re-scheduled.
Closes #658
> feat: handle provisioned errors gracefully

- base-requirements.txt
- test-requirements.txt
keep it in test-requirements (implying cpython for now)
issue #560 
I might shuffle the requirements around a bit soon so keeping this simple for now (i.e. no pypy-test-requirements.txt yet)
> chore: remove the wsaccel dependency on pypy

- autopush/router/fcm.py
- autopush/router/gcm.py
- autopush/router/webpush.py
- autopush/tests/test_router.py
- autopush/utils.py
- autopush/web/message.py
While moving to UUIDs is noble, they're not fully JSON encodable.
Normalize ChannelIDs to strings where possible.
closes #691
> bug: normalize channelids to JSON encodable entities

- autopush/tests/test_websocket.py
- autopush/web/message.py
- autopush/websocket.py
> bug: Stop splitting version info when logging for websocket

- autopush/utils.py
> fix: Set TTL to 0 if None when doing expiration checks

- autopush/router/apnsrouter.py
- autopush/router/fcm.py
- autopush/router/gcm.py
- autopush/tests/test_router.py
- autopush/tests/test_websocket.py
- autopush/utils.py
Marshmallow converts "-" to "_", and some header values are stored with
slightly different names.
closes #702
> fix: correct headers to use transcoded values

- autopush/tests/test_websocket.py
- autopush/websocket.py
this was now dead code only misused by tests
closes #706
> fix: kill websocket.Notification

- autopush/db.py
- autopush/tests/test_websocket.py
- autopush/websocket.py
have websocket log them instead of passing along to sentry and give them
a metric
closes #703
> fix: improve handling of JSONResponseErrors

- autopush/router/apns2.py
- autopush/router/apnsrouter.py
- autopush/router/fcm.py
- autopush/router/gcm.py
- autopush/tests/test_router.py
Previous bridge connection error severity has been reduced for
non-critical errors. In addition, a new metric set has been created for
connection specific errors. Ops should monitor
`updates.client.bridge.(fcm|gcm|apns).connection_err` for sudden spikes.
Closes #715
> bug: Add metrics for connection errors, reduce level for other errors

- autopush/db.py
- autopush/settings.py
- autopush/tests/test_db.py
- autopush/tests/test_endpoint.py
- autopush/tests/test_integration.py
- autopush/tests/test_websocket.py
- autopush/utils.py
- autopush/web/push_validation.py
- autopush/websocket.py
Alleviates heavy writes to remove messages by instead timestamping
messages and skipping through them. The first message record
retains the timestamp that was read up to for later use.
Closes #661
> feat: skip timestamped messages instead of deleting

- autopush/websocket.py
Increases random interval for rotation reschedule to  30 minutes.
Closes #723
> feat: spread monthly rotation retry over 30 minutes

- autopush/db.py
- autopush/settings.py
- autopush/tests/test_db.py
Ensures the date argument is passed along with the table name
when creating the rotating message table during the
get_rotating_message_table call.
Closes #722
> feat: retain date when checking message tables

- autopush/exceptions.py
- autopush/main.py
- autopush/settings.py
- autopush/tests/test_main.py
- autopush/tests/test_websocket.py
- autopush/websocket.py
> fix: reset UAID if too many messages are pending

- autopush/tests/test_websocket.py
- autopush/websocket.py
Users whom have no record version should now be reset after
message checks have completed.
Closes #711
> feat: reset users missing a record version or expired version

- autopush/web/base.py
> fix: Add exception info to log.info call

- autopush/crypto_key.py
- autopush/tests/test_cryptokey.py
- autopush/web/webpush.py
and add type hints to crypto_key
closes #750, issue #712
> fix: handle CryptoKeyExceptions in new crypto validation

- autopush/logging.py
- autopush/router/simple.py
- autopush/tests/test_logging.py
- autopush/tests/test_web_validation.py
- autopush/web/base.py
- autopush/web/simplepush.py
- autopush/web/webpush.py
Add's full request timing with validation and routing break-outs. Also logs the request
and validation timing even if validation fails or routing otherwise errors out.
Closes #758
> feat: Add request timing w/validation breakdown.

- autopush/base.py
- autopush/tests/test_integration.py
assuming nothing minds newlines in this value: sys.version should suffice
> feat: log the python version in client_info

- autopush/tests/test_integration.py
- autopush/web/base.py
Our 410's should result in the sender no longer sending, but senders
ignore this. To avoid excessive re-processing on repeats, 410's now
include a Cache-Control header set to the max of 1 day for nginx to
cache results.
Closes #770
> feat: add cache-control header to 410's

- autopush/base.py
- autopush/ssl.py
- autopush/tests/test_integration.py
in addition to allowing them with unauthorized certs
also add some partner endpoint log tests
fixes #771
> feat: allow log_check/status/health API calls w/out certs

- autopush/logging.py
- autopush/tests/test_integration.py
otherwise its buffer pointlessly keeps around 65k old log message events for replaying
fixes #786
This should improve our memory usage
e.g. I was getting endpoint/connection up towards almost 1gb/360mb rss w/ about 15min of load from a bunch of aplt's notification_forever. With this fix we hover more around 225/190mb, maybe 250/200mb tops with more time/load thrown at it. Measurements all done on a local linux VM under pypy 5.6.0
> fix: prefer the LogBeginner observer entry point

- autopush/main.py
- autopush/tests/test_integration.py
- autopush/tests/test_main.py
- configs/autopush_endpoint.ini.sample
now toggles exposing a separate port w/ proxy protocol handling
fixes #788
> feat: switch proxy_protocol -> proxy_protocol_port

- autopush/router/apns2.py
- autopush/tests/test_router.py
> bug: APNs library requires parameters to be strings

- CONTRIBUTING.md
> docs: add git signing note

- .coveragerc
- autopush/gcdump.py
- autopush/main.py
- autopush/memusage.py
- autopush/tests/test_integration.py
- autopush/tests/test_main.py
- autopush/web/health.py
- base-requirements.txt
for debugging our memory usage
issue #802 
(includes gcdump.py from pypy with slight changes to process the result of pypy's gc.dump_rpy_heap)
> add a /_memusage API on a separate (internal port)

- docs/http.rst
> bug: Correct docs to use correct HTTP method for subscription updates

- autopush/router/gcm.py
- autopush/tests/test_router.py
GCM messages that trigger a "fail" were attempting to update
registration with insufficient data. It's better to treat them like
other GCM errors and report back, but take no additional actions.
Also increased testing around these sorts of errors.
closes #828
> bug: Do not attempt to register failed GCM registrations

- autopush/tests/test_websocket.py
- autopush/websocket.py
- tox.ini
There's no need to log exceptions failing to save a message for a
user that has been deleted. Now a metric will be emitted instead.
This also tweaks the tox runner to no longer include object memory
tracking by default.
Closes #811
> feat: capture and metric item not found instead of log

- autopush/metrics.py
- autopush/tests/test_metrics.py
avoids the host resolver preventing flushing of the queued up metrics
in some cases
fixes #840
> fix: prefer the create method

- autopush/db.py
- autopush/tests/test_endpoint.py
- autopush/web/registration.py
- docs/http.rst
Adds new bridge system HTTP endpoint to fetch a list of server known
CHIDs for a given UAID. Useful for remote clients to check status. (see
documentation for calling structure and return).
Also fixed an edge case where clients that may have been forced offline
due to external system errors could still register new endpoints. The
behavior will now be to return a 410 error if a client has been flagged
as disconnected by the server. It is up to the client to check the local
bridge connection and re-establish any endpoints.
closes: #844, #843
> feat: Add ChannelID report for UAID

- autopush/router/apnsrouter.py
- autopush/tests/test_router.py
> bug: Use log.failure() to better track exceptions in APNS

- autopush/jwt.py
- autopush/tests/test_endpoint.py
- autopush/tests/test_web_validation.py
- autopush/utils.py
- autopush/web/webpush.py
- docs/api.rst
- docs/api/jwt.rst
- requirements.txt
- test-requirements.txt
Switches to using python cryptography library instead of jose/jwt
(which relied on python ecdsa library). Also discovered lots of fun
discrepencies between how ecdsa and libssl sign things.
closes #785
> feat: Use cryptography based JWT parser for increased speed

- autopush/tests/test_integration.py
- autopush/web/webpush.py
> bug: Limit exception trapping to known types when processing crypto-key

- autopush/router/apns2.py
- autopush/router/apnsrouter.py
- requirements.txt
> bug: APNS may close a socket prematurely, resulting in an AttributeError

- autopush/router/gcm.py
- autopush/tests/test_web_validation.py
- autopush/tests/test_web_webpush.py
- autopush/web/webpush.py
> bug: enforce `senderID` for gcm/fcm

- autopush/jwt.py
- autopush/tests/test_endpoint.py
- autopush/tests/test_log_check.py
- autopush/tests/test_web_webpush.py
- autopush/web/base.py
- autopush/web/health.py
- autopush/web/log_check.py
- autopush/web/message.py
- autopush/web/registration.py
- autopush/web/simplepush.py
- autopush/web/webpush.py
> refactor: refine the Handler validation

- autopush/tests/test_endpoint.py
- autopush/web/registration.py
was causing more trouble than it's worth for clients
also add an already passing test for #867 (fixed in b1312db)
fixes #880, #867
> fix: revert registration's strict critical failure check

- autopush/base.py
- autopush/web/base.py
- autopush/web/simplepush.py
- autopush/web/webpush.py
- autopush/websocket.py
- parquet_schemas/README.md
- parquet_schemas/autopush/push.cfg
Adds a unified parquet stream for all log messages with a message
matcher for necessary endpoint and connection node messages.
Logging fields were cleaned up for consistency and status code
logging uses a 0 instead of "" to avoid mixing types.
Closes #874, #882
> feat: add parquet unified schema and cleanup logging messages

- autopush/tests/test_integration.py
- autopush/tests/test_websocket.py
- autopush/websocket.py
Logs a summary of session statistics when a client drops its client
connection. Also cleans up several places where the PushState had
its uaid set but not its uaid_obj or uaid_hash.
Closes #448
> feat: add session log summary on connection close

- autopush/router/simple.py
- autopush/tests/test_websocket.py
- autopush/websocket.py
When handling provisioned errors, the same logic should be used as when
a JSONResponseError occurs.
Closes #744
> feat: handle JSONResponse errors like provisioned errors

- autopush/router/apnsrouter.py
- autopush/tests/test_router.py
> feat: temporarily allow aps data via registration message

- autopush/http.py
- autopush/tests/client.py
- autopush/tests/test_client.py
- autopush/tests/test_endpoint.py
- autopush/web/message.py
(from:
https://github.com/fiorix/cyclone/blob/c1f830e/cyclone/testing/client.py
https://github.com/fiorix/cyclone/blob/9f0dff1/cyclone/tests/test_testing.py
-> test_client.py)
refactor test_endpoint around it & inlineCallbacks
issue #871
> refactor: bring in cyclone trunk's testing client

- autopush/router/apns2.py
- autopush/tests/test_router.py
> bug: Serialize Decimal correctly for ios aps

- autopush/http.py
- autopush/logging.py
- autopush/tests/support.py
- autopush/tests/test_health.py
- autopush/tests/test_integration.py
- autopush/tests/test_log_check.py
- autopush/tests/test_web_validation.py
- autopush/tests/test_web_webpush.py
- mypy.ini
and remove mypy's deprecated fast_parser option
issue #871
> refactor: convert handler tests to client/inlineCallbacks

- autopush/http.py
- autopush/tests/test_endpoint.py
- autopush/web/registration.py
- docs/http.rst
The existing bridge API was overly permissive on parameters and
difficult to follow on necessary values. As a result this became
a bit larger than originally anticiated and is a refactor of the
bridge API into distinct handlers for each distinct URL path with
re-usable and specific validation schema's.
Closes #893
> feat: avoid triggering validation errors from bridge API

- autopush/tests/test_websocket.py
generalize the waiting code w/ a _wait_for
closes #871 
I'll note that _send_messsage could easily return the result of get_response, leaving that for later if we really want it
> refactor: convert to inlineCallbacks

- autopush/router/apnsrouter.py
- autopush/tests/test_integration.py
- autopush/tests/test_router.py
- autopush/web/registration.py
This is a 'quick' patch to get a testable version in the hands of
outside parties quickly. A future fix will limit the 'aps' payload
option only to the 'dev' platform.
issue #910
> feat: switch to new iOS mutable aps payload

- autopush/logging.py
- autopush/tests/test_logging.py
Under no load, the Firehose logger spun the CPU because the max
of (MAX_INTERVAL-time_since_sent, 0) always resulted in 0. This
is because the time_since_sent became quite large, and the
MAX_INTERVAL was only 30 resulting in a high negative number. 0
was the max, so the loop would spin.
What was actually intended was to never wait more than MAX_INTERVAL
before trying to send a batch. That requires taking the min value
since last sent or the MAX_INTERVAL.
> fix: avoid firehose logger spinning the CPU

- autopush/tests/test_websocket.py
- autopush/web/simplepush.py
- autopush/websocket.py
For logging consistency on the backend we should use the same type
for logging values for the same key. Simplepush was logging its
version as an int however.
Closes #925
> fix: ensure simplepush messages log message_id as str

- autopush/router/fcm.py
- autopush/router/gcm.py
- autopush/tests/test_integration.py
- autopush/web/webpush.py
closes #930 
NOTE: pjenvey: If this conflicts with your refactor, this has lower priority.
> feat: accept aes128gcm content encoding

- autopush/http.py
- autopush/main.py
- autopush/router/__init__.py
- autopush/router/simple.py
- autopush/router/webpush.py
- autopush/settings.py
- autopush/tests/test_endpoint.py
- autopush/tests/test_integration.py
- autopush/tests/test_router.py
- autopush/tests/test_websocket.py
- autopush/web/health.py
- autopush/websocket.py
> refactor: split clients and agent off settings

- autopush/db.py
- autopush/main.py
- autopush/metrics.py
- autopush/router/apnsrouter.py
- autopush/router/fcm.py
- autopush/router/gcm.py
- autopush/router/simple.py
- autopush/router/webpush.py
- autopush/settings.py
- autopush/tests/test_integration.py
- autopush/tests/test_router.py
- autopush/tests/test_web_base.py
- autopush/tests/test_websocket.py
- autopush/utils.py
- autopush/web/base.py
- autopush/web/registration.py
- autopush/web/simplepush.py
- autopush/web/webpush.py
- autopush/websocket.py
Closes #943 
(Metric updates from https://docs.google.com/spreadsheets/d/18RL-Brz-Q-jR-iClNPCwDMVPYS0P2CvkHSJ2WZK-ceA/edit#gid=0)
> feat: Use modern metrics

- autopush/db.py
- autopush/tests/test_endpoint.py
- autopush/tests/test_websocket.py
- autopush/web/registration.py
- autopush/websocket.py
> bug: add logging for register/unregister calls for websocket and bridges

- autopush/router/apnsrouter.py
- autopush/router/fcm.py
- autopush/router/gcm.py
- autopush/router/simple.py
- autopush/router/webpush.py
- autopush/tests/test_integration.py
- autopush/tests/test_web_base.py
- autopush/tests/test_websocket.py
- autopush/web/base.py
- autopush/web/simplepush.py
- autopush/web/webpush.py
- autopush/websocket.py
The metric increments were being called for registration API
calls due to an error callback. They weren't called for success
cases as well. Moving them to the lower callbacks with a new
flag should help ensure they're incremented correctly.
Closes #958
> fix: move metric increments to lowest callbacks

- .travis.yml
and switch to its more recent pypy
(trusty's becoming travis' default and it's already getting more recent pypy builds vs precise)
> chore: upgrade travis to trusty

- autopush/web/base.py
- autopush/web/registration.py
- autopush/web/webpush.py
and fix ChannelRegistrationHandler now taking a UUID chid after the
last refactor and some type sigs
Closes #984
> fix: hasher doesn't take UUIDs

- autopush/db.py
- autopush/diagnostic_cli.py
- autopush/http.py
- autopush/main.py
- autopush/router/webpush.py
- autopush/settings.py
- autopush/tests/support.py
- autopush/tests/test_health.py
- autopush/tests/test_integration.py
- autopush/tests/test_log_check.py
- autopush/tests/test_main.py
- autopush/tests/test_web_base.py
- autopush/tests/test_websocket.py
- autopush/utils.py
- autopush/websocket.py
specify read/write_throughput settings in initial/update rotating
tables
remove some unneeded moto usage
Closes #956
Closes #928
> refactor: postpone any db table creation/lookup into db.setup()

- autopush/tests/__init__.py
- autopush/tests/test_db.py
- autopush/tests/test_diagnostic_cli.py
- autopush/tests/test_endpoint.py
- autopush/tests/test_health.py
- autopush/tests/test_integration.py
- autopush/tests/test_main.py
- autopush/tests/test_router.py
- autopush/tests/test_utils.py
- autopush/tests/test_web_validation.py
- autopush/tests/test_web_webpush.py
- autopush/tests/test_websocket.py
Moves the local DynamoDB run to the package level and all tests use
it instead of running moto's incomplete dynamodb mock.
This also fixes a bug in the tests that left autopush.db.key_hash
set after an endpoint test ran.
> feat: remove use of moto dynamodb2 from tests

- autopush/web/webpush.py
Added "updates.notification.encoding.{content-encoding}",
we already track vapid as "updates.vapid.{version}"
Closes #992
> bug: Add missing metric for notification encoding

- autopush/config.py
- autopush/http.py
- autopush/main_argparse.py
- autopush/router/__init__.py
- autopush/tests/test_endpoint.py
- autopush/tests/test_integration.py
- autopush/tests/test_main.py
- autopush/tests/test_websocket.py
- autopush/websocket.py
Due to a last minute change in the prior patch, the initial state of the
config option was improperly set. In addition the simplepush
registration was succeeding when it should have been rejected. Added
testing to verify both conditions are satisfied.
Closes #994
> bug: change "enable_simplepush" flag to "disable_simplepush"

- autopush/config.py
- autopush/main_argparse.py
- autopush/router/webpush.py
- autopush/tests/test_main.py
- autopush/tests/test_router.py
- autopush/tests/test_websocket.py
- autopush/websocket.py
> feat: remove unused udp wake capability

- autopush/tests/test_webpush_server.py
- autopush_rs/__init__.py
- autopush_rs/src/server.rs
> fix: use websocket hostname for server binding

- autopush/db.py
- autopush/tests/test_db.py
- autopush/web/health.py
> fix: ensure we paginate through all table names

- autopush_rs/Cargo.toml
tok-io has an expensive debug assertion, this turns them all off for now.
> fix: remove debug assertions

- autopush_rs/Cargo.lock
- autopush_rs/Cargo.toml
Mostly just disable the TLS features in tungstenite/tokio-tungstenite as we
don't use them anyway!
> refactor: Remove unneeded features from Rust deps

- autopush_rs/Cargo.lock
- autopush_rs/src/server/mod.rs
Focus on retaining just one `Timeout` instance instead of creating many, using
the `reset` function where possible. Additionally try to streamline the number
of timers that we hit during each pass to ensure that we're at most only hitting
one on the fast path.
> refactor: Reorganize the Rust ping manager

- autopush/tests/test_webpush_server.py
- autopush/webpush_server.py
- autopush_rs/src/call.rs
- autopush_rs/src/client.rs
> fix: don't check storage for new uaid's

- autopush_rs/Cargo.lock
- autopush_rs/src/call.rs
- autopush_rs/src/errors.rs
- autopush_rs/src/http.rs
- autopush_rs/src/protocol.rs
- autopush_rs/src/queue.rs
- autopush_rs/src/rt.rs
- autopush_rs/src/server/dispatch.rs
- autopush_rs/src/server/mod.rs
- autopush_rs/src/server/webpush_io.rs
- autopush_rs/src/util/mod.rs
- autopush_rs/src/util/rc.rs
- autopush_rs/src/util/send_all.rs
> feat: update cargo deps, and rustfmt all the rust

- autopush/db.py
- autopush/router/webpush.py
> bug: Remove discussion comment and useless bool return

- autopush/memusage.py
just in case objgraph pollutes its output
Closes #1028
> fix: dump_rpy_heap before calling objgraph

- autopush/config.py
- autopush/main_argparse.py
- autopush/tests/test_main.py
- autopush/tests/test_web_base.py
- autopush/web/base.py
> feat: add Strict-Transport-Security header

- autopush/tests/test_endpoint.py
- autopush/tests/test_integration.py
- autopush/web/registration.py
- autopush/web/webpush.py
Some older records in the database appear to have been miscategorized as
"simplepush". We should try to handle those as "webpush".
Closes #1033
> bug: Handle legacy simplepush records as candidate webpush records

- .coveragerc
- autopush/db.py
- autopush/tests/conftest.py
- autopush/tests/test_cryptokey.py
- autopush/tests/test_db.py
- autopush/tests/test_diagnostic_cli.py
- autopush/tests/test_endpoint.py
- autopush/tests/test_health.py
- autopush/tests/test_integration.py
- autopush/tests/test_log_check.py
- autopush/tests/test_logging.py
- autopush/tests/test_main.py
- autopush/tests/test_metrics.py
- autopush/tests/test_router.py
- autopush/tests/test_utils.py
- autopush/tests/test_web_base.py
- autopush/tests/test_web_validation.py
- autopush/tests/test_web_webpush.py
- autopush/tests/test_webpush_server.py
- autopush/tests/test_websocket.py
- test-requirements.txt
Issue #1039
General sweep of tests to make things "pytest" compliant. This means switching nosetool calls for their assert/pytest primatives. 
Note, there were a few tests in test_cryptokey that were invalid and have been fixed because of this.
In addition, some [light type correction](https://github.com/mozilla-services/autopush/compare/bug/1033?expand=1#diff-8c7a1b5174dad635894310a2ce89eb88L104) was made where appropriate.
(Also note: this PR does not fully close #1039. tox and other functions still use nose.)
> feat: move tests to pytest

- autopush/config.py
- autopush/db.py
- autopush/main.py
- autopush/main_argparse.py
- autopush/ssl.py
- autopush/tests/test_main.py
- autopush/tests/test_ssl.py
- autopush/webpush_server.py
avoids unnecessary allocation of them which appears to stress pypy's
GC (w/ their finalization needs)
also fix some type signatures and kill some now unnecessary mock patches
Closes: #1038
> feat: cache SSLContexts created by ssl.wrap_socket

- autopush/noseplugin.py
- autopush/router/apns2.py
- autopush/router/apnsrouter.py
- autopush/router/gcm.py
- autopush/tests/certs/makecerts.py
- autopush/tests/test_integration.py
- autopush/tests/test_web_base.py
- autopush/websocket.py
- configs/autopush_shared.ini.sample
Converts two errors into metrics and attempts retry on Connection or
HTTP2 errors.
Closes #1052
> feat: address HTTP2 errors in APNS

- autopush/ssl.py
- autopush/tests/test_web_webpush.py
- autopush/web/webpush.py
> fix: drop users with no router_type recorded

- .travis.yml
- automock/boto.cfg
- autopush/__init__.py
- autopush/db.py
- autopush/tests/__init__.py
- autopush/tests/test_db.py
- autopush/tests/test_endpoint.py
- autopush/tests/test_health.py
- autopush/tests/test_integration.py
- autopush/tests/test_web_base.py
- autopush/tests/test_webpush_server.py
- autopush/tests/test_websocket.py
- autopush/utils.py
- autopush/web/base.py
- autopush/web/health.py
- autopush/web/webpush.py
- autopush/webpush_server.py
- autopush/websocket.py
- tox.ini
> feat: convert to use AWS boto3

- autopush/tests/test_webpush_server.py
- autopush/webpush_server.py
- autopush_rs/Cargo.lock
- autopush_rs/Cargo.toml
- autopush_rs/__init__.py
- autopush_rs/src/call.rs
- autopush_rs/src/client.rs
- autopush_rs/src/errors.rs
- autopush_rs/src/lib.rs
- autopush_rs/src/protocol.rs
- autopush_rs/src/server/metrics.rs
- autopush_rs/src/server/mod.rs
the rust side's metrics (via cadence) currently lack the ability to
pass datadog tags, currently ua.{message_data,connection.lifespan}
Issue: #1054
> feat: fill in missing metrics for autopush_rs

- autopush/__init__.py
- autopush/db.py
to avoid potential conflicts when merging changes to __version__
> refactor: move MAX_EXPIRY out of __init__

- autopush_rs/Cargo.lock
- autopush_rs/Cargo.toml
- autopush_rs/src/lib.rs
- autopush_rs/src/server/mod.rs
> feat: add sentry panic reporting

- autopush/memusage.py
- autopush/tests/test_integration.py
- autopush/web/health.py
> feat: make memusage's objgraph/dump_rpy_heap optional

- autopush/db.py
- autopush/diagnostic_cli.py
- autopush/tests/test_db.py
- autopush/tests/test_diagnostic_cli.py
Also we were inconsistent about passing `current_month` when registering
`webpush` protocol entities. While not strictly an error now, it could
cause issues later if we do stricter lookups.
Closes #1096
> bug: Fix diagnostic cli to handle tuple args

- autopush/main.py
- autopush/metrics.py
- autopush/tests/test_metrics.py
emitted every 15 seconds per datadog's preferred minimum
Closes #1093
> feat: add some metrics for twisted's threadpool

- .gitignore
- autopush/tests/test_integration.py
- autopush/tests/test_z_main.py
- autopush/webpush_server.py
- autopush_rs/src/call.rs
- autopush_rs/src/client.rs
- autopush_rs/src/http.rs
- autopush_rs/src/protocol.rs
Adds the following functionality for capability parity:
- Skip sending messages if the message is expired
- Properly handle legacy messages in a message stream
- Set appropriate flags for a uaid not found in the db
- Always return a timestamp when querying into timestamp messages
- Send messages in the order they're retrieved from the db
- Accept messages from endpoint while waiting for acks
- Don't save TTL:0 messages in the db if the client fails to ack them
- Allow TTL:None from endpoint and treat as TTL:0
Closes #1060
> feat: add integration testing for Rust connection node

- autopush_rs/Cargo.lock
- autopush_rs/Cargo.toml
- autopush_rs/src/server/mod.rs
- autopush_rs/src/server/tls.rs
update openssl and hyper usage per their new deprecations
Issue #1104
> feat: upgrade rust deps to latest

- Makefile
- requirements.txt
- tox.ini
remove the with_gmp=no pycrypto+pypy workaround as the new python-jose
replaces pycrypto w/ pycryptodome
Closes #1104
> feat: update python dependencies to the latest versions

- autopush/logging.py
- autopush/tests/test_logging.py
frames should be sorted from oldest to newest despite raven's
iter_stack_frames
Closes #1134
> fix: reverse our filled in stack trace order

- autopush/config.py
- autopush/db.py
- autopush/logging.py
- autopush/main.py
- autopush/memusage.py
- autopush/metrics.py
- autopush/tests/test_utils.py
- autopush/utils.py
- autopush/webpush_server.py
- autopush_rs/Cargo.lock
- autopush_rs/Cargo.toml
- autopush_rs/__init__.py
- autopush_rs/src/lib.rs
- autopush_rs/src/server/mod.rs
- autopush_rs/src/util/aws.rs
- autopush_rs/src/util/mod.rs
cleanup instance id or hostname used for logging/metrics and duplicate
some of that setup in rust (which'll eventually need it anyway)
some mypy fixes, update to cadence release
Closes #1113
> fix: bind autopush_rs to all interfaces to match python

- autopush/tests/test_web_base.py
- autopush/tests/test_websocket.py
- autopush/web/base.py
- autopush/websocket.py
by treating ClientError as we originally treated boto2's
JSONResponseError
centralize endpoint's ClientError handling into _boto_err (kills
_overload_err as it's all now handled in one place)
Issue #1138
> fix: handle InternalServerErrors (ClientError subclass)

- autopush/db.py
- autopush/exceptions.py
- autopush/router/webpush.py
- autopush/tests/__init__.py
- autopush/tests/test_db.py
- autopush/tests/test_integration.py
- autopush/tests/test_router.py
- autopush/tests/test_web_validation.py
- autopush/tests/test_webpush_server.py
- autopush/types.py
- autopush/utils.py
- autopush/web/health.py
- autopush/web/registration.py
- autopush/web/webpush.py
- autopush/webpush_server.py
- autopush/websocket.py
- requirements.in
- requirements.txt
it was previously handling only the old boto2 JSONResponseError in
those spots
also kill the remaining boto2 bits
Closes #1138
> fix: have webpush router handle ClientErrors

- autopush/db.py
- autopush/tests/test_db.py
- autopush/tests/test_integration.py
- autopush/utils.py
Also enforce expiry on router records
Closes #1073
> bug: fix _expiry() function to use seconds

- autopush_rs/src/client.rs
- autopush_rs/src/protocol.rs
- autopush_rs/src/server/mod.rs
- autopush_rs/src/util/megaphone.rs
- autopush_rs/src/util/mod.rs
Handles broadcast subscriptions per client, holds a single broadcast
change set tracker, and sends out broadcasts at the ping interval to
clients that have new broadcast deltas to send.
Issue #1129 
Note: Only remaining work is to add the megaphone polling portion that grabs the broadcast master list and keeps it up to date.
> feat: add megaphone broadcast handling, ping check, server tracking

- autopush/config.py
- autopush/main.py
- autopush/main_argparse.py
- autopush_rs/Cargo.toml
- autopush_rs/__init__.py
- autopush_rs/src/server/mod.rs
- autopush_rs/src/util/megaphone.rs
Megaphone API is now queried on startup and at every poll interval to
update the change state tracker.
Issue #1129 
Remaining work after this is going to be a fairly large set of integration tests to close out the issue.
> feat: add megaphone API query and repeating service updating

- autopush/tests/test_db.py
> bug: add missing setup_module() function to test_db

- autopush_rs/Cargo.lock
- autopush_rs/Cargo.toml
- requirements.txt
both python and rust side
hold off on a woothee-rust update for now in case the API changes back
Closes #1170
> feat: update dependencies

- autopush/tests/test_log_check.py
- autopush/tests/test_rs_integration.py
- autopush/web/log_check.py
- autopush_rs/__init__.py
also:
- ensure log_check always calls finish
- quiet the megaphone BaseHTTPRequestHandler error seen during shutdown
Closes #1173
> fix: wrong toggling of autopush_rs's json_logging

- .travis.yml
- automock/boto.cfg
- autopush/tests/test_webpush_server.py
- autopush/webpush_server.py
- autopush_rs/Cargo.lock
- autopush_rs/Cargo.toml
- autopush_rs/src/call.rs
- autopush_rs/src/client.rs
- autopush_rs/src/lib.rs
- autopush_rs/src/protocol.rs
- autopush_rs/src/server/mod.rs
- autopush_rs/src/util/ddb_helpers.rs
- autopush_rs/src/util/mod.rs
Removes the asserts when adding the uaid to the uaids hash, and issue
proper disconnect call to existing client. Ensure uaid removal removes
the right client indicated by a separate UUID per client object.
Convert IncrementStorage call to pure Rust async and remove Python
implementation.
Closes #1177
> feat: fix asserts on client dis/connect and convert inc call to rust

- autopush_rs/Cargo.lock
- autopush_rs/Cargo.toml
- autopush_rs/src/client.rs
- autopush_rs/src/lib.rs
- autopush_rs/src/protocol.rs
- autopush_rs/src/server/mod.rs
- autopush_rs/src/util/megaphone.rs
Switch to using the futures state machine to separate out client
state from the implementation.
Closes #1181
> feat: refactor client state machine

- autopush_rs/src/call.rs
- autopush_rs/src/client.rs
- autopush_rs/src/http.rs
- autopush_rs/src/lib.rs
- autopush_rs/src/protocol.rs
- autopush_rs/src/rt.rs
- autopush_rs/src/server/mod.rs
- autopush_rs/src/server/tls.rs
- autopush_rs/src/util/autojson.rs
- autopush_rs/src/util/megaphone.rs
- autopush_rs/src/util/rc.rs
- autopush_rs/src/util/send_all.rs
We had previously run rustfmt over a few files, but not everything. Here it is run over everything. 
Note that the other PR for porting the check storage command should be merged first as this goes after that commit to avoid conflicts with it.
> rustfmt all the rust

- autopush/webpush_server.py
- autopush_rs/src/client.rs
> fix: don't save legacy messages from the Rust node

- autopush/http.py
- autopush/tests/test_integration.py
- autopush/web/base.py
> fix: endpoint now returns a JSON-based 404 for all 404's

- .travis.yml
- autopush/tests/test_integration.py
- autopush/tests/test_rs_integration.py
- autopush/tests/test_webpush_server.py
- autopush/webpush_server.py
- autopush_rs/Cargo.lock
- autopush_rs/Cargo.toml
- autopush_rs/__init__.py
- autopush_rs/src/call.rs
- autopush_rs/src/client.rs
- autopush_rs/src/lib.rs
- autopush_rs/src/server/mod.rs
- autopush_rs/src/util/ddb_helpers.rs
> feat: port register command to Rust

- autopush/tests/test_webpush_server.py
- autopush/webpush_server.py
- autopush_rs/src/call.rs
- autopush_rs/src/client.rs
- autopush_rs/src/util/ddb_helpers.rs
> feat: port drop user command to Rust

- .travis.yml
- Dockerfile
- Dockerfile.python27
- autopush_rs/Cargo.lock
- autopush_rs/Cargo.toml
- autopush_rs/build.rs
- autopush_rs/src/call.rs
- autopush_rs/src/queue.rs
- autopush_rs/src/server/mod.rs
- requirements.txt
- setup.py
- tox.ini
requires a couple workarounds:
- rename queue::Sender -> AutopushSender to avoid cbindgen bug w/ type aliases:
https://github.com/eqrion/cbindgen/issues/131
- make structs not representable in C opaque (remove #[repr(C)])
- have to pin to an older serde_derive for now because cbindgen does
Closes #1045
> feat: switch from snaek to milksnake

- autopush/tests/test_rs_integration.py
- autopush/tests/test_webpush_server.py
- autopush/webpush_server.py
- autopush_rs/src/call.rs
- autopush_rs/src/client.rs
- autopush_rs/src/util/ddb_helpers.rs
Add's Rust integration test to verify the direct message is stored that
was not present before.
Closes #1208
> feat: port store messages command to Rust

- autopush_rs/src/client.rs
- autopush_rs/src/db/commands.rs
- autopush_rs/src/db/mod.rs
In separate commits:
Attempting impl trait in db.mod, it moves the boxing calls into client.rs but doesn't buy us much at all in here otherwise.
Moved as much as the metrics as possible (without refactoring lookup_user) out of db.mod: they really don't belong in there
and fixed the weird indents
> refactor: more impl trait, etc

- Dockerfile
- Dockerfile.python27
- autopush/tests/test_rs_integration.py
by nuking the rustup install & target dir after installation
Issue #1232
> fix: shrink the Docker build

- autopush_rs/src/db/commands.rs
lost this in the python port
Issue #1249
> fix: ensure consistent_read on fetch messages fns

- autopush/tests/test_integration.py
We don't actually need to test legacy notification saving here, since
this is supposed to test monthly table rotation. The test would fail
randomly based on whether the channel UUID started with the first two
characters being less than '01' as fetch_timestamp_messages requires
that to locate them.
Closes #878
> fix: remove legacy notification saving to address intermittent fails

- autopush/router/webpush.py
- autopush/websocket.py
and ignore another ProvisionedThroughputExceeded case
Closes #1267, #1268
> fix: emit metrics for Direct messages and client nack codes

- autopush/diagnostic_cli.py
- autopush/tests/test_diagnostic_cli.py
- docs/testing.rst
> feat: improve endpoint_diagnostic tool and documents

- autopush/config.py
- autopush/main_argparse.py
- autopush/router/__init__.py
- autopush/router/adm.py
- autopush/tests/test_integration.py
- autopush/tests/test_z_main.py
- autopush/web/registration.py
- autopush/web/webpush.py
- configs/autopush_endpoint.ini.sample
- docs/adm.rst
- docs/glossary.rst
- docs/install.rst
> feat: add ADM support

- autopush/http.py
- autopush/tests/test_health.py
- autopush/web/dockerflow.py
- version.json
> feat: add dockerflow callbacks for endpoint

- autopush/router/gcm.py
- autopush/router/gcmclient.py
- autopush/tests/test_gcmclient.py
- autopush/tests/test_integration.py
- autopush/tests/test_router.py
- requirements.txt
> feat: make gcm calls use async callbacks

- .travis.yml
- autopush/logging.py
- requirements.in
- requirements.txt
- test-requirements.txt
but avoid the latest marshmallow (2.17.0 spams us with strict=True
warning changes and 3.0 is still beta)
and adapt to http://github.com/getsentry/raven-python/pull/1261
switch travis to xenial for pypy6 (so grpcio builds)
Closes #1311
> chore: upgrade dependencies

- .travis.yml
- Dockerfile
also fixes the outdated debian jessie sources.list
Closes #1327
> chore: bump to latest pypy

- requirements.txt
per CVE-2019-11324 affecting < 1.24.2
..I'm kinda avoiding updating the remaining dependencies until we give the new pypy 7 a run (its utf8 string representation change is pretty big)
> chore: update urllib

- autopush/tests/test_integration.py
- autopush/web/webpush.py
> fix: handle TypeErrors too

- autopush/tests/test_fcmclient.py
- autopush/tests/test_gcmclient.py
- autopush/tests/test_integration.py
- requirements.txt
and adapt tests to it
Closes #1336
> chore: bump to the latest twisted per CVE-2019-12387

- requirements.txt
- test-requirements.txt
Due to later versions of pyutil no longer supporting 2.7, I've locked to the last working version.
Depending on how pyup does it's detection, we may need to segregate these sorts of version lockdowns to their own, ignored `requirements.txt` file until we can replace this with a rust version.
Library update. Tests should return nominally
N/A - Scheduled update.
> chore: Library update

- .circleci/config.yml
to avoid deploy steps potentially picking up a previous merge build
that wrote to the cache out of order
Describe these changes.
We don't get this random error that breaks deployment:
```
Failed to clean image:  <...>/pipelines/autopush:1.55.0-282 Command '('docker', 'rmi', '<...>/pipelines/autopush:1.55.0-282')' returned non-zero exit status 1.
Traceback (most recent call last):
File "./bin/pull-verify-push", line 188, in <module>
main(sys.argv)
File "./bin/pull-verify-push", line 160, in main
verify_digest_circleci(src_build_url, src_digest)
File "./bin/pull-verify-push", line 130, in verify_digest_circleci
raise Exception("Digest: {} not found in {}".format(digest, build_url))
Exception: Digest: sha256:4970b3ab3f7f830d4eb715114594eca312f0f732403b328dd246da0b84dd960a not found in …
```
> chore: include CIRCLE_TAG in the cache key

- Dockerfile
- autopush/base.py
- autopush/router/apnsrouter.py
- autopush/tests/test_integration.py
Includes better logging for uncaught APNs errors, since those were
getting dropped by cyclone.
Tests included in integration suite.
Addresses Issue #1383
Closes #1384
> bug: do not require `encryption` header for APNs `aes128gcm` encoded messages

- CHANGELOG.md
- autopush/__init__.py
Retagging 1.55.2 to fix the version number in code (`__init__.py`) and cleanup the CHANGELOG (pulling out 1.55.2).
Otherwise identical from pulled 1.55.2:
https://github.com/mozilla-services/autopush/compare/1.55.2...1.55.3
> chore: tag 1.55.3

- autopush/crypto_key.py
The `CryptoKey.get_label` method has an example which was inaccurate.
N/A
N/A
> docs: Fix CryptoKey.get_label example

- test-requirements.txt
The latest pytest-cov (2.10.0) requires pytest >= 4.6. 4.6 is the last version to support Python 2.7. The CI was using pytest 4.3 instead, which caused issues on https://github.com/mozilla-services/autopush-rs:
https://travis-ci.org/github/mozilla-services/autopush-rs/builds/697653480
pytest-cov changelog:
https://github.com/pytest-dev/pytest-cov/blob/4cbd3bb5ef8a501aeafbca21d22622210fe604a6/CHANGELOG.rst#2100-2020-06-12
N/A
N/A
> chore: Upgrade pytest to 4.6 to fix pytest-cov dependency

- autopush/tests/test_db.py
- autopush/tests/test_integration.py
- autopush/web/registration.py
The original unit tests left questions as to whether or not an `update()` token change altered other data associated with the registered endpoint. Added integration tests to verify that the data remains consistent after a token update request is processed.
also fixed a typo, and due to a change in ssl handling, added some skip tests if an older cert is used. 
This is a test.
Closes #1397
> bug: Add integration tests to verify that updates do not alter reg info

- autopush/metrics.py
- autopush/router/webpush.py
- autopush/tests/test_db.py
- autopush/tests/test_metrics.py
- autopush/tests/test_z_main.py
- autopush/web/webpush.py
- docs/api/metrics.rst
- requirements.txt
While this package does not use the officially sanctioned "markus"
metrics package, it does use the same Datadog library.
*Reviewer Note*: this replaces #1401, which does a lot more (replaces metrics libraries with `markus`, changes base tag handling, etc.) This PR carries less risk for a service that's being rewritten anyway.
Unit tests included.
Closes #1400
> feat: Add tags back to metrics.

- autopush/metrics.py
- autopush/tests/test_integration.py
- autopush/tests/test_metrics.py
- docs/api/metrics.rst
- requirements.in
- requirements.txt
remove datadog's ThreadStats (as it only speaks datadog's http protocol)
w/ markus backed by the plain statsd compatible Datadog backend
upgrade datadog to avoid its own telemetry metrics producing garbage
tags
Note:
This is simplified from #1401 and has a couple other fixes:
- markus is actually expecting the original datadog style tags arguments we currently use e.g. `['foo:bar', 'baz:quux']`, and the PR had a few straggler uses of the old style anyway, so kept what we have
- fixes passes them along via the `tags=` kwarg it expects
- doesn't pass the namespace option to Datadog (as markus inserts it for us)
Running against a local statsd collector produces expected metrics + tags
Closes #1400
> feat: fixup metrics + tags

- autopush/metrics.py
Closes #1408
Put markus in the corner, because it's degrading latency.
Verify latency does not deteriorate under load.
Closes #1408
> bug: put markus metric handling on a deferred thread

- autopush/metrics.py
- autopush/tests/test_metrics.py
- autopush/web/webpush.py
- autopush/websocket.py
The metric calls were blocking. It was recommended that they be wrapped
by a discrete thread handler.
How should reviewers test?
Issue: #1408
> bug: regression: wrap metric calls in thread handler

- autopush/metrics.py
- autopush/tests/test_integration.py
queue metrics up for one single thread emitter to avoid adding every
metric call to twisted's thread pool
Describe these changes.
Metrics are still emitted
Closes #1408
> fix: followup for 1408

- autopush/metrics.py
- autopush/tests/test_integration.py
- autopush/tests/test_metrics.py
- requirements.in
- requirements.txt
Brings back TwistedMetrics backed by our custom txstatsd w/ tags support
Metrics emitted during runtime, e.g. `nc -l -u 8125`
Closes #1413
> fix: switch back to TwistedMetrics (w/ our custom txstatsd)

- autopush/router/apns2.py
- autopush/router/apnsrouter.py
- autopush/tests/test_integration.py
- autopush/tests/test_router.py
- autopush/web/base.py
- autopush/web/webpush.py
Closes #1414
We were not deleting users if the bridge was reporting that the associated user token was unregistered or invalid. This may have lead to impolite behavior by autopush
Tests included
Closes #1414, https://github.com/mozilla-services/autopush/issues/1383
> bug: delete users if bridge connection reports they're gone

- autopush/router/adm.py
- autopush/router/apnsrouter.py
- autopush/tests/test_integration.py
- autopush/tests/test_router.py
- autopush/web/base.py
* normalized metric name and tags
Closes #1421
* made the APNS user disconnect metric more generic across all mobile platforms
* normalized some tag information
Tests included. 
Closes #1421.
> feat: add metric for all mobile bridge "unregistered" user drops

- autopush/router/webpush.py
- autopush/tests/test_integration.py
- autopush/tests/test_router.py
The intended behavior of the WebPush router is to return HTTP 201 if the message was directly delivered to the node, or HTTP 202 if the message could not be directly delivered and was instead stored for later delivery. The code was incorrectly returning 201 for both cases.
Tests have been updated, and should pass.
N/A
> fix: Return HTTP 202 if the WebPush message is stored instead of delivered

- autopush/router/apnsrouter.py
- autopush/router/fcm_v1.py
- autopush/router/fcmv1client.py
- autopush/tests/test_router.py
Issue #1373
This is a really quick patch to try and capture the relevant details returned from FCM when it returns an INVALID_ARGUMENT error. I had thought it was related to the TTL, but we already trim it down to an appropriate max value. 
Honestly, if I could figure out how to trigger this in dev, I'd be thrilled. As it is, to test this you'll need a valid FCM routing number, which means compiling an emulated FCM client app (the sample one works fine) which means updating Android Studio to 5, and fetching the latest updates, before altering the code paths and java code to match the FCM project you declared so that the downloaded google-services.json file tied to the sample app you declared in FCM match then use a combination of registration and send scripts to try to trigger an …
> bug: report details of an FCM "INVALID_ARGUMENT" error

- autopush/tests/test_integration.py
- autopush/web/webpush.py
use `endpoint_url` instead of `hostname` for VAPID aud checks.
Provide a different `endpoint_hostname` instead of `hostname` (e.g. `localhost` instead of `127.0.01`) and verify that only audiences using the matching host name are allowed.
Closes #1434.
> bug: compare VAPID aud to endpoint_hostname 

- .circleci/config.yml
Follows up #1438 with additional fix mentioned in https://github.com/mozilla-services/Dockerflow/pull/60/files
> bug: add docker auth to docker image pulls

- autopush/router/webpush.py
- autopush/tests/test_integration.py
- autopush/tests/test_router.py
- requirements.txt
This version ensures that we return a status code of 201 for all subscription updates. According to https://tools.ietf.org/html/rfc8030#section-5.1 only Push Subscriptions with Receipts should ever return 202, and those are currently not supported by Autopush.
This also includes an update flagged by dependabot.
Tests included.  Verification can be done by sending a push message while the recipient device is "offline".
Closes #1443.
> bug: return 201 for all push subscription requests.

- CHANGELOG.md
- autopush/__init__.py
*   update circleci to use new docker auth ([a4f66c0b](https://github.com/mozilla-services/autopush/commit/a4f66c0b8dfe6164d2ac02d2adaf08a5cd285fef))
*   return 201 for all push subscription requests. (#1446) ([b0279078](https://github.com/mozilla-services/autopush/commit/b027907896798506736d87fe25bfb624fa3e0632), closes [#1443](https://github.com/mozilla-services/autopush/issues/1443))
*   add docker auth to docker image pulls ([3d90ec8d](https://github.com/mozilla-services/autopush/commit/3d90ec8dcd5f2939378cd8bd61a63cbb1fb8d67e))
> chore: tag 1.58.3

- autopush/router/apnsrouter.py
- autopush/router/fcm.py
- autopush/router/fcm_v1.py
- autopush/tests/test_router.py
- autopush/web/base.py
Adds add'l metric tags to autopush endpoint bridge.errors (pairs to https://github.com/mozilla-services/autopush-rs/pull/291)
Closes #1454
> feat: Add status code and errno to bridge.error metrics

- autopush/router/apns2.py
- autopush/router/apnsrouter.py
- requirements.txt
Closes #1457
Add the APNS error reason to the `notification.bridge.error` tags. This is a work around to expose the APNS error so that we can determine failure causes for APNS.
Closes #1457
> feat: add apns error reason to the metric reporting
