Makefile
test-requirements.txt

* Add `make lint`.
* Add a test requirements file for installing test dependencies.

Add test requirements, linting

---

autopush/main.py
autopush/tests/test_main.py
requirements.txt
setup.py

Add sentry usage and basic main execution.

---

autopush/db.py
autopush/main.py
autopush/settings.py
autopush/tests/test_db.py

Add table naming and provisioning throughput options.

---

autopush/db.py
autopush/settings.py
autopush/tests/test_db.py
autopush/websocket.py
setup.cfg

Add metrics to provision errors.

---

autopush/db.py

Remove hardcoded table names

---

autopush/endpoint.py
autopush/main.py
autopush/tests/test_endpoint.py
autopush/tests/test_websocket.py
autopush/websocket.py

* Fix missing `settings` attribute errors.
* Fix encoding errors by converting URLs to bytes.
* Only respond with a 202 for routing misses.
@bbangert r?

Smoke test fixes

---

autopush/main.py
autopush/ssl.py

Adds the ability to use a certificate chain file and turns off SSLv3.

ssl: add AutopushSSLContextFactory

---

autopush/main.py
autopush/ssl.py

SSL - enable mozilla intermediate policy

---

autopush/logging.py

EnvVersion for logs needs to be 2.0.

logging: EnvVersion -> 2.0

---

autopush/tests/test_websocket.py
autopush/websocket.py

My feeble attempt at a botnet was discovered.

Reject non-`dict` messages

---

autopush/main.py
autopush/settings.py

remove hard coded ping interval and data values

---

autopush/main.py
autopush/tests/test_websocket.py

Ensure we pass both options to the `AutopushSettings` constructor.

Fix `{min_ping_interval, pong_delay}` setting

---

autopush/tests/test_websocket.py
autopush/websocket.py

Track deferreds and remove them on client shutdown.

---

autopush/tests/test_websocket.py
autopush/websocket.py

Bring websocket testing near 100%

---

autopush/main.py

Fix regex to allow /register and /register/

Fix regex to make register have optional end slash

---

autopush/tests/test_endpoint.py
autopush/tests/test_router.py
autopush/tests/test_websocket.py

assert_called is not fully supported.
@bbangert || @kitcambridge r?
cc: @crodjer

Convert ...assert_called to assert(...called)

---

CHANGELOG.rst
autopush/tests/test_websocket.py
autopush/websocket.py

Fixes an issue with ack updates possibly having a None value.

Fix bug with ack'ing a None

---

autopush/main.py
autopush/tests/test_main.py
autopush/websocket.py

Add `/status` to the connection node

---

CHANGELOG.rst
autopush/db.py
autopush/endpoint.py
autopush/tests/test_endpoint.py
autopush/tests/test_integration.py

...And store those blobs in DynamoDB binary fields.

Base64-encode Web Push message blobs

---

autopush/tests/test_integration.py
autopush/websocket.py

Fix routing errors for blank updates with headers

---

autopush/websocket.py

Fix attribute errors caused by premature closures

---

CHANGELOG.rst
autopush/router/simple.py
autopush/tests/test_router.py

Check for stale connection nodes when routing

---

autopush/endpoint.py
autopush/websocket.py

* Fix #50 patch to set env in Hello handler, not send_json
* Fix bad hash encoding in endpoint
@bbangert r?

Code fixes for env and hash

---

Makefile
configs/autopush_connection.ini
configs/autopush_endpoint.ini
docs/install.rst
docs/testing.rst

* Removed pypy dependencies
* updated docs to include system dependecies modeled after install on
virgin EC2
* Updated docs to include new testing info
resolves #197
@bbangert r?

Updated docs/makefile

---

autopush/main.py

* endpoint_hostname and endpoint_scheme now shared values
* default back to previous behaviors
fixes #186
@bbangert r?

set autoendpoint to read proper config values

---

CHANGELOG.rst
autopush/endpoint.py
autopush/router/interface.py
autopush/router/simple.py
autopush/router/webpush.py
autopush/tests/test_endpoint.py
autopush/tests/test_integration.py
docs/api/endpoint.rst

* Add actionable JSON errors to the Endpoint responses. Issue #178.
Closes #178.
@jrconlin r?

Make errors in the HTTP endpoint usable

---

docs/api.rst
docs/install.rst

* Add index document for new senderid rst doc
resolves #173 
@bbangert r?

add add'l build flags and libraries from #173

---

CHANGELOG.rst
autopush/main.py
configs/autopush_connection.ini
configs/autopush_shared.ini

Fix HOSTNAME to not conflict with env  (resolves #198)
Move endpoint_* config vars to shared ini 
supersedes #202 
@bbangert r?

Fix HOSTNAME env & move endpoint_* to shared

---

CHANGELOG.rst
autopush/main.py
autopush/settings.py
autopush/tests/test_websocket.py
autopush/websocket.py
configs/autopush_connection.ini

Add hello timeout

---

doc-requirements.txt
docs/api/utils.rst

May have caused RTD failure.
@bbangert r?

Removed old call from utils doc

---

autopush/main.py
autopush/router/gcm.py
autopush/senderids.py
autopush/tests/test_main.py
autopush/tests/test_router.py
autopush/tests/test_senderids.py

Convert SenderID refresh to TimerService. 
Resolves #230. 
@bbangert r?

Convert SenderID to use TimerService

---

autopush/senderids.py
autopush/tests/test_senderids.py

Follow up to prior patch. 
Move to Looping Call (which only starts the clock when the last call finishes)

Move to looping call & r's

---

CHANGELOG.rst
autopush/endpoint.py
autopush/main.py
autopush/settings.py
autopush/tests/test_endpoint.py
configs/autopush_endpoint.ini

* Fix issue with auth_key args.
* Removed bogus default cryptokey
@bbangert r?

Merge 1.8.1 to master

---

CHANGELOG.rst
autopush/main.py

Fix endpoint to not require local certs for TLS

---

CHANGELOG.rst
autopush/tests/test_db.py

bug: fix db test to do month addition properly

---

CHANGELOG.rst
autopush/endpoint.py
autopush/tests/test_endpoint.py

Capture authorization header for logging in endpoint requests

---

CHANGELOG.rst
docs/index.rst

Adds endpoint names to the docs.
Closes #223.
@jrconlin r?

Add docs about endpoints and websocket locations

---

CHANGELOG.rst
docs/running.rst

Fix running documentation to indicate how to use the dynamodb local server

---

CHANGELOG.rst
autopush/endpoint.py
autopush/router/simple.py
autopush/settings.py
autopush/tests/test_endpoint.py
autopush/tests/test_main.py

bug: Fix startup issue with rotating message table not being created.

---

autopush/endpoint.py
autopush/tests/test_endpoint.py

Tag requests with a unique ID

---

CHANGELOG.rst
autopush/endpoint.py
autopush/tests/test_endpoint.py

bug: fix issue with gcm router not being passed appropriate params.

---

autopush/endpoint.py

I noticed this while reviewing #272. We were calling `make_endpoint` in the thread pool, but not `register_channel`. No changelog entry, since the HTTP API is new in this release.
@bbangert r?

Move blocking channel registration to a thread pool

---

CHANGELOG.rst
autopush/endpoint.py
docs/index.rst

Make HTTP API a deep link

---

autopush/metrics.py

bug: Add self param for metric sink. Resolves #274.

---

autopush/db.py
autopush/endpoint.py
autopush/tests/test_endpoint.py
autopush/tests/test_integration.py
autopush/utils.py
autopush/websocket.py

issue #229
Since it was popping up in multiple files & classes, moved
write_error to utils and added pass-thoughs to classes.
@bbangert r?

Add write_error override to other handlers

---

CHANGELOG.rst
autopush/endpoint.py
autopush/router/gcm.py
autopush/tests/test_endpoint.py
autopush/tests/test_integration.py
autopush/tests/test_router.py

@bbangert || @kitcambridge  r?
Will need to notify @ncalexan before change is pushed to

feature: Pass Encryption-Key xor Crypto-Key. Fixes #258.

---

CHANGELOG.rst
autopush/endpoint.py
docs/running.rst

Removed reference to obsolete test package

---

CHANGELOG.rst
autopush/__init__.py
autopush/db.py
autopush/tests/test_websocket.py
autopush/websocket.py

This also add's a flag to autopush.db allowing all provisioned method calls
to be logged and introspected for testing.
Fixes #300

bug: fix extra db writes on new uaid connect

---

CHANGELOG.rst
autopush/__init__.py
autopush/tests/test_integration.py
autopush/websocket.py

bug: fix connections with invalid UAID from pre-uaid hashing

---

CHANGELOG.rst
autopush/__init__.py
autopush/tests/test_websocket.py
autopush/websocket.py

Add use_webpush base tag to metrics

---

docs/install.rst

Fix docs to reflect current reality

---

CHANGELOG.rst
maintenance.py

Add's the next months message table automatically, and updates if
necessary to the latest read/write units from the current month.
Closes #254

feat: add maintenance.py script for use in AWS Lambda

---

CHANGELOG.rst
autopush/router/simple.py
autopush/tests/test_router.py

Add logging if router connection is refused.

---

CHANGELOG.rst
autopush/websocket.py

bug: capture more types of exceptions that happen when nodes disappear

---

CHANGELOG.rst
autopush/__init__.py
autopush/router/gcm.py

@bbangert r?
new branch because git.

Remove unused "ver" from GCM bridge data.

---

CHANGELOG.rst
autopush/endpoint.py
autopush/tests/test_endpoint.py
autopush/tests/test_integration.py
docs/http.rst

Require TTL header for incoming Subscription events.

---

CHANGELOG.rst
autopush/endpoint.py
autopush/router/webpush.py
autopush/tests/test_integration.py
autopush/tests/test_router.py

Add "Location" to outbound webpush responses

---

autopush/tests/test_endpoint.py
autopush/utils.py

bug: handle well-known exported pub key formats

---

autopush/endpoint.py
autopush/tests/test_endpoint.py
autopush/tests/test_websocket.py
autopush/websocket.py

feat: add user-agent logging to acks

---

autopush/router/webpush.py
autopush/tests/test_integration.py
autopush/websocket.py

fix: ensure ttl is set to 0 when missing for send

---

autopush/tests/test_websocket.py
autopush/websocket.py

Nack messageTypes are now accepted for websocket clients and will be logged
along with the code. Unregister may now include a code and a log message
will be emitted for unregister commands including a code. Ack's also log
the code if included.
Closes #380 
@jrconlin r?

feat: accept nack messages, log code for ack/unreg/nack

---

autopush/db.py
autopush/tests/test_db.py
autopush/tests/test_integration.py
autopush/tests/test_websocket.py

fix: clear only the node_id in the router record

---

autopush/main.py
autopush/tests/test_integration.py
autopush/tests/test_websocket.py
requirements.txt
test-requirements.txt

feat: bump autobahn/twisted reqs to 0.13/16.0 for utf8 fix

---

autopush/endpoint.py

bug: Allow arbitrary args for options and head functions

---

.travis.yml

chore: add slack travis output

---

Dockerfile

* remove MAINTAINER - it creates an extra layer
* FROM an offical docker image
* use /app by convention
* don't worry about trimming -dev packages

Dockerfile changes:

---

autopush/endpoint.py
autopush/router/apnsrouter.py
autopush/tests/test_endpoint.py

Also fixes flake8 spacing error in router/apnsrouter.
closes #432 
@bbangert r?

feat: Add extended err message for old encryption

---

autopush/endpoint.py
autopush/health.py
autopush/logging.py
autopush/main.py
autopush/senderids.py
autopush/tests/test_endpoint.py
autopush/tests/test_websocket.py
autopush/utils.py
autopush/websocket.py

Declare the arguments for raven to hopefully prevent key corruption
Closes #460 
@bbangert r?

bug: Wrap twisted formatEvent in a try handler

---

autopush/router/webpush.py
autopush/tests/test_integration.py
autopush/tests/test_router.py

Add full checks for preflight failure conditions.
Closes #461 
@bbangert r?

fix: Check connected month bounds for preflight

---

default.nix

A basic default for nix-shell for nix usage that eases development.
@jrconlin r?

chore: add default.nix for nix/nixos users

---

circle.yml

[Dockerflow](https://github.com/mozilla-services/Dockerflow)

Add CircleCI for dockerflow

---

autopush/logging.py
autopush/tests/test_logging.py

fix: add integration testing and verification of sentry reporting

---

autopush/logging.py

Twisteds new logging does not use the 'failure' key at all, the
prior assumptions it would exist caused key exceptions instead
of reporting errors. This fix changes to only the new style of
failure checking.
Issue #493 
@jrconlin r?

fix: remove failing key check from sentry logging

---

autopush/tests/test_main.py

Two of the tests for update_rotating_tables failed to account for
a different code-path that runs at the end of the month when the
next day is a new month. This change populates the next month
message table entry so that it won't matter if its the end of
the month or not for the tests to run properly.
Closes #502 
@jrconlin r?

fix: handle different behavior in rotating table tests at month-end

---

autopush/router/gcm.py

Increase reporting priority for GCM errors so that they are logged to
Kibana. Made some messaging more unique and descriptive of actual case.
closes: #505 
@bbangert r?

bug: Elevate GCM reported error states

---

autopush/main.py

fix: restore pragma line for full coverage

---

autopush/tests/test_websocket.py

was probably unintentional in 874f0757

test: don't hide wait_for_times test failures

---

autopush/endpoint.py
autopush/router/webpush.py
autopush/tests/test_endpoint.py
autopush/web/base.py
autopush/web/validation.py
autopush/websocket.py

Added some additional, descriptive logging for duplicate error conditions.
closes #354 
@bbangert r?

feat: Add URLs, text to error response messages

---

autopush/tests/test_websocket.py
autopush/websocket.py

feat: log all unregister/register calls

---

autopush/main.py
autopush/settings.py
autopush/tests/test_main.py

fix: kill now unused senderid_list cruft

---

doc-requirements.txt
pypy-requirements.txt
requirements.txt
test-requirements.txt

fix: readline isn't needed

---

docs/install.rst

The Makefile assumes PyPy and we're going in that direction so defaulting to it

docs: updates to installation

---

autopush/crypto_key.py
autopush/endpoint.py
autopush/tests/test_endpoint.py

fix: fix _base_tags class var usage and make other class vars immutable

---

autopush/endpoint.py
autopush/web/base.py
autopush/web/validation.py
autopush/websocket.py

these async write calls don't return anything so this makes the intent more clear, especially amid callbacks
r? @bbangert @jrconlin

refactor: clarify intent of write methods returning nothing

---

docs/index.rst
docs/releasing.rst

closes #538 
r? @jrconlin, @pjenvey

docs: add release process

---

default.nix

fix: remove readline from the nix pkg also

---

autopush/web/base.py
autopush/web/webpush.py

forgot a few more of these
r? @jrconlin

refactor: prefer immutable class vars (follow up to 97a133a4)

---

docs/releasing.rst

closes #586 
@pjenvey r?
(I appreciate the level of effort that will be required)

bug: fixes reference to releasing page

---

autopush/main.py

docs: kill outdated comment

---

configs/autopush_connection.ini.sample
docs/running.rst

This is probably enough for #565, for now
r? @jrconlin

docs: describe configuration of SSL/TLS

---

autopush/endpoint.py

bug: Check tokens in constant time

---

autopush/tests/test_web_validation.py
autopush/web/validation.py

marshmallow may be more "helpful" than we'd like.
Closes #604 
@bbangert r?

bug: Prevent invalid header values from causing key errors in validation

---

autopush/db.py
autopush/endpoint.py
autopush/tests/test_db.py
autopush/tests/test_endpoint.py
autopush/tests/test_web_base.py
autopush/tests/test_web_validation.py
autopush/web/base.py
autopush/web/validation.py

bug: Trap BOTO Server exception as 503's

---

autopush/logging.py
autopush/tests/test_logging.py

it's sent as sentry's top level stacktrace vs its explicit exception stacktrace
issue #613
r? @bbangert @jrconlin

feat: send sentry the current stack when lacking a Failure tb

---

autopush/tests/test_websocket.py
autopush/websocket.py

closes #618 
r? @jrconlin @pjenvey

fix: disable log_exception capturing in tests

---

Makefile

closes #548 
@pjenvey @bbangert r?

bug: update Makefile to use correct requirements

---

docs/http.rst

There was confusion about the various token references. These are
clarified with simpler references and more distinct labels.
closes #627

bug: clarify token references in HTTP endpoint docs

---

autopush/tests/test_endpoint.py

test: clarify where we mean IRouter vs db.Router

---

autopush/base.py
autopush/endpoint.py
autopush/health.py
autopush/log_check.py
autopush/main.py
autopush/tests/test_endpoint.py
autopush/tests/test_health.py
autopush/tests/test_integration.py
autopush/tests/test_web_base.py
autopush/tests/test_web_webpush.py
autopush/tests/test_websocket.py
autopush/utils.py
autopush/web/base.py
autopush/web/simplepush.py
autopush/web/webpush.py
autopush/websocket.py

Some cleanup while I was in here -- more than I originally intended. I extracted into the new BaseHandler to make sure PyCharm was as happy as it can be. There's more that can go into it, but enough for now
r? @jrconlin @bbangert

cleanup ap_settings

---

autopush/router/apnsrouter.py
autopush/router/fcm.py
autopush/router/gcm.py
autopush/settings.py
autopush/tests/test_main.py
autopush/tests/test_router.py

fix: return webpush style response for bridged users

---

autopush/db.py
autopush/endpoint.py
autopush/router/webpush.py
autopush/tests/test_web_webpush.py
autopush/web/webpush.py
autopush/websocket.py

fix: log all drop_user calls with record details when possible

---

autopush/endpoint.py
autopush/exceptions.py
autopush/settings.py
autopush/tests/test_endpoint.py
autopush/tests/test_web_validation.py
autopush/utils.py
autopush/web/base.py
autopush/web/validation.py
base-requirements.txt

Newest library allows for better detection.
closes #641 
@bbangert r?

feat: update jwt library

---

autopush/main.py
autopush/router/apns2.py
autopush/router/apnsrouter.py
autopush/tests/test_main.py
autopush/tests/test_router.py
base-requirements.txt
configs/autopush_shared.ini.sample
tox.ini

Existing libraries either lack tests or are not good matches for
twisted. Created a very light weight apns2 library that does connection
pooling and sends out the new notification. Connection pooling is
strongly suggested by APNs docs.
closes: #662

feat: Switch to new http2 based APNS protocol

---

autopush/endpoint.py

For bogus or invalid Authorization headers, an extra write could occur
after finish.
closes #665

fix: remove extra jws_err handler which caused extra write after finish

---

autopush/db.py
autopush/endpoint.py
autopush/router/apnsrouter.py
autopush/router/webpush.py
autopush/tests/test_db.py
autopush/tests/test_endpoint.py
autopush/tests/test_integration.py
autopush/tests/test_router.py
autopush/tests/test_web_validation.py
autopush/tests/test_websocket.py
autopush/utils.py
autopush/web/base.py
autopush/web/simplepush.py
autopush/web/validation.py
autopush/web/webpush.py
autopush/websocket.py
base-requirements.txt
docs/http.rst

Add's webpush topics with versioned sort key.
Closes #643

feat: add webpush topics

---

.noserc
setup.cfg

feat: include timestamps in tests' logs

---

autopush/tests/test_db.py
autopush/tests/test_diagnostic_cli.py
autopush/tests/test_endpoint.py
autopush/tests/test_integration.py
autopush/tests/test_logging.py
autopush/tests/test_main.py
autopush/tests/test_metrics.py
autopush/tests/test_router.py
autopush/tests/test_web_base.py
autopush/tests/test_web_webpush.py
autopush/tests/test_websocket.py

this leaves us with 3 asserts. they're in non-test code (preflight_check and authenticate_peer_cert)
Closes #674.

issue 674: kill asserts

---

autopush/web/health.py
autopush/web/log_check.py
autopush/web/registration.py
autopush/web/simplepush.py
autopush/web/webpush.py

bug: validated methods ignore raw arguments

---

autopush/router/fcm.py
autopush/router/gcm.py
autopush/tests/test_router.py

fix: do not return error informtion for 500 errors for router

---

autopush/settings.py
autopush/web/message.py

fix: simplify Message validation by passing WebPushNotification

---

autopush/tests/__init__.py
autopush/utils.py

feat: add type hints to autopush/utils.py

---

autopush/router/apns2.py
autopush/router/apnsrouter.py
autopush/router/fcm.py
autopush/tests/test_integration.py

Integration tests patch as close to send as possible.
issue: #692

feat: Add integration tests for bridges

---

autopush/db.py
autopush/tests/test_db.py

fix: Zero pad months in table names

---

autopush/endpoint.py
autopush/tests/test_endpoint.py
autopush/web/base.py

fix: Don't log exceptions that don't want to be logged

---

autopush/main.py
autopush/tests/test_main.py
autopush/tests/test_router.py
configs/autopush_connection.ini.sample
configs/autopush_endpoint.ini.sample
configs/autopush_shared.ini.sample

also cleanup some config options

fix: kill lingering doc references to S3

---

autopush/tests/test_integration.py
autopush/tests/test_logging.py
autopush/web/simplepush.py
autopush/web/webpush.py

fix: log router_key in web/webpush web/simplepush

---

autopush/main.py
autopush/tests/test_integration.py
autopush/tests/test_main.py
configs/autopush_endpoint.ini.sample

allows the endpoint to get remote client ips from the ELB in proxy mode
closes #761

feat: add a --proxy_protocol for the partner endpoint

---

autopush/tests/test_web_validation.py
autopush/web/base.py

they lack the right mocks for them (as of d963d18)
fixes #780

fix: avoid the new webpush validation in these tests

---

docs/http.rst

feat: Typos in docs

---

base-requirements.txt

bug: Update to latest cryptography library

---

autopush/main.py
autopush/tests/test_integration.py
autopush/tests/test_websocket.py
autopush/websocket.py

also cleanup ap_settings passthru via a PushServerFactory
fixes #805 
(supersedes #803)

fix: ensure our LoopingCall failures are logged

---

autopush/settings.py
autopush/tests/test_integration.py
autopush/tests/test_web_webpush.py
autopush/web/simplepush.py

bug: VAPID errors should return 401, not 404

---

autopush/tests/test_web_validation.py
autopush/web/webpush.py

We now attempt to coerce the jwt exp value in case it wasn't an int
and verify that it is within the next 24 hours and has not already
expired.
Closes #794

feat: add thorough jwt exp validation

---

autopush/memusage.py
autopush/tests/test_integration.py
autopush/web/health.py

fix: fix coverage

---

docs/releasing.rst

docs: git tag needs an explicit signing flag (and msg)

---

.travis.yml
Makefile
autopush/logging.py
autopush/main.py
autopush/noseplugin.py
autopush/websocket.py
mypy.ini
tox.ini

and try running mypy on travis
issue #712

fix: a couple minor type sig changes

---

.coveragerc
autopush/memusage.py
autopush/tests/test_integration.py

fix: really fix coverage

---

Makefile
tox.ini

fix: try to avoid build failures on pypy w/ with_gmp=no

---

autopush/haproxy.py
autopush/main.py
autopush/tests/test_integration.py
autopush/websocket.py

fix: impl. a haproxy endpoint that actually wraps SSL

---

CHANGELOG.md
autopush/__init__.py

tagging a 1.25.1 just for the partner endpoint on stage (to get #824)

chore: tag 1.25.1

---

autopush/main.py
autopush/router/apns2.py
autopush/router/fcm.py
autopush/router/gcm.py
autopush/settings.py
autopush/tests/test_router.py

bug: Don't send non-priority messages to sentry

---

autopush/memusage.py
autopush/tests/test_integration.py

feat: also include pypyjit's get_stats_asmmemmgr

---

.travis.yml

feat: new slack channel

---

autopush/main.py
autopush/protocol.py
autopush/router/simple.py
autopush/router/webpush.py
autopush/settings.py
autopush/tests/test_main.py

feat: Add timeout for internally routed messages.

---

Dockerfile

chore: peg the pypy version

---

autopush/router/apnsrouter.py
autopush/tests/test_endpoint.py
autopush/web/base.py
autopush/web/registration.py

* Return 400 code for missing registration token
* check form issing UAID for GET channel calls
* check for null value headers on write
closes #857

bug: Fixes for missing UAID and header values

---

autopush/settings.py
autopush/tests/test_integration.py
autopush/tests/test_web_validation.py
autopush/tests/test_web_webpush.py
autopush/utils.py
autopush/web/base.py
autopush/web/webpush.py

VAPID Draft-02 <https://tools.ietf.org/html/draft-ietf-webpush-vapid-02>
alters how VAPID information can be provided to the server.
closes #826

feat: Add support for VAPID DRAFT 02 

---

autopush/jwt.py
autopush/tests/test_integration.py

bug: Do not report InvalidSignature as unhandled

---

autopush/tests/test_integration.py
autopush/web/webpush.py

feat: add tracking for content-encoding

---

autopush/diagnostic_cli.py
autopush/exceptions.py
autopush/http.py
autopush/main.py
autopush/main_argparse.py
autopush/settings.py
autopush/tests/test_integration.py
autopush/tests/test_logging.py
autopush/tests/test_main.py
autopush/tests/test_websocket.py
autopush/websocket.py
setup.py

- drive apps from settings as much as possible
- push some initialization into customized factories
- split arg parsing out into its own module
fixes #465

refactor: rearrange main around app (MultiService) objects

---

parquet_schemas/autopush/autopush.autoendpoint.docker.autoendpoint.cfg
parquet_schemas/autopush/autopush.autopush.docker.autopush.cfg

feat: update parquet schema for unified parquet logging

---

autopush/tests/test_endpoint.py
autopush/tests/test_integration.py
autopush/utils.py
autopush/web/webpush.py

* Fix some flake8 spacing
closes #902

bug: Trap for missing Vapid AUTH header token

---

autopush/tests/test_integration.py
autopush/web/registration.py

bug: Ensure 'aps' passes through marshmallow schema check

---

autopush/logging.py
autopush/tests/test_logging.py

fix: log boolean values

---

Dockerfile

feat: upgrade to pypy 5.8.0

---

autopush/memusage.py
autopush/tests/test_integration.py

issue #802 
Merging this into release/1.32 to attempt a quick 1.32.1 tag w/ just this

feat: dump pmap -XX/X if available

---

autopush/tests/test_integration.py
autopush/web/registration.py

bug: Return 400 if routing token is blank or unspecified

---

autopush/main.py
autopush/metrics.py
autopush/tests/test_utils.py
autopush/utils.py

feat: log EC2 instance ID when using AWS for hostname

---

autopush/router/apns2.py
autopush/router/fcm.py
autopush/router/gcm.py
autopush/tests/test_websocket.py
autopush/web/base.py
autopush/web/message.py
autopush/web/registration.py
autopush/web/simplepush.py
autopush/web/webpush.py
autopush/websocket.py

feat: demote info to debug to reduce logging messages

---

autopush/http.py
autopush/main.py
autopush/main_argparse.py
autopush/settings.py
autopush/tests/test_endpoint.py
autopush/websocket.py

refactor: convert AutopushSettings to attrs

---

autopush/jwt.py

(reopening closed #939)
related to cffi issue #320: pypy's GC isn't aware of many of
cryptography's allocations, manually add pressure for now so it keeps
up
temporarily toggleable so we can experiment w/ it vs the cryptography
recent leak fix (cryptography PR 3732)
Closes #917

fix: add memory pressure for jwt's cryptography usage

---

autopush/tests/test_websocket.py
autopush/websocket.py

refactor: convert PushState to attrs

---

autopush/jwt.py
autopush/tests/test_utils.py
autopush/utils.py
autopush/web/webpush.py

feat: Do not do VAPID auth on trusted connections

---

.pyup.yml
CONTRIBUTING.md
Makefile
autopush/noseplugin.py
requirements.in
requirements.txt
test-requirements.txt

also upgrade deps via pip-tools: and kill the unneeded future dep and
move pycrypto into tests only
also title case the Issue/Closes footer in CONTRIBUTING
Closes: #949
Issue: #454

chore: add a pyup config file

---

.pyup.yml

pyup's global update apparently doesn't apply to it
Issue: #949

chore: explicitly set update on requirements.txt

---

autopush/db.py

refactor: give DatabaseManager some saner defaults

---

.pyup.yml

chore: fix syntax

---

autopush/main.py
autopush/main_argparse.py
autopush/settings.py
autopush/tests/test_integration.py
autopush/tests/test_web_validation.py
autopush/tests/test_web_webpush.py
autopush/utils.py
autopush/web/webpush.py
requirements.in
requirements.txt

feat: make cryptography lib optional

---

autopush/http.py
autopush/main.py
autopush/main_argparse.py
autopush/router/__init__.py
autopush/router/simple.py
autopush/router/webpush.py
autopush/settings.py
autopush/tests/test_endpoint.py
autopush/tests/test_integration.py
autopush/tests/test_main.py

Preliminary work for removing simplepush protocol by making it optional
(default off)
Issue #799

feat: make simplepush protocol optional

---

requirements.in
requirements.txt

chore: upgrade to latest cryptography

---

autopush/router/webpush.py

fix: actually defer this requests.post call

---

autopush/tests/test_integration.py
autopush/web/registration.py
docs/http.rst

bug: allow only known protocols for /register calls

---

.coveragerc
.travis.yml
Dockerfile
Dockerfile.python27
autopush/main.py
autopush/tests/test_webpush_server.py
autopush/webpush_server.py
autopush_rs/Cargo.lock
autopush_rs/Cargo.toml
autopush_rs/__init__.py
autopush_rs/src/call.rs
autopush_rs/src/client.rs
autopush_rs/src/errors.rs
autopush_rs/src/http.rs
autopush_rs/src/lib.rs
autopush_rs/src/protocol.rs
autopush_rs/src/queue.rs
autopush_rs/src/rt.rs
autopush_rs/src/server.rs
autopush_rs/src/util/mod.rs
autopush_rs/src/util/rc.rs
autopush_rs/src/util/send_all.rs
requirements.txt
setup.py
states.dot
test-requirements.txt
tox.ini

Implements a complete Rust proof of concept Push server using a queue
to send future calls to complete to a Python threaded server. The
Python side contains an extraction of the websocket logic, following
an intended call pattern documented in states.dot.
Co-Authored-By: Alex Crichton <alex@alexcrichton.com>
Co-Authored-By: Philip Jenvey <pjenvey@underboss.org>
Closes #978

feat: initial Rust proof of concept implementation

---

.gitignore
autopush_rs/Cargo.lock
autopush_rs/Cargo.toml
autopush_rs/src/call.rs
autopush_rs/src/errors.rs
autopush_rs/src/lib.rs
autopush_rs/src/server/dispatch.rs
autopush_rs/src/server/mod.rs
autopush_rs/src/server/webpush_io.rs

This adds some logic to parse an incoming HTTP request, peek at the headers, and
then route the response appropriately.

Add a `/status` handler on the ws port

---

autopush_rs/__init__.py
autopush_rs/src/server/mod.rs

fix: resolve hostnames and send pings out

---

maintenance.py

fix: ensure lambda script paginates through all table names

---

autopush_rs/src/server/mod.rs

These may have been the cause of some of the errors y'all saw when under load maybe?

A few small Rust ping-pong fixes

---

Dockerfile

feat: upgrade to pypy 5.9.0

---

autopush/tests/test_integration.py
requirements.in
requirements.txt
test-requirements.txt

also:
* adapt to pyfcm 1.4's breaking changes:
https://github.com/olucurious/PyFCM/releases/tag/1.4.0
* move the snaek dep to requirements.in where it belongs
* remove a couple duplicates in test-requirements
Closes #1040

feat: update dependencies to the latest versions

---

.travis.yml
setup.py
tox.ini

also update travis to (hopefully) latest pypy
Closes: #1046

chore: allow WITH_RUST=false to disable the rust build

---

autopush/router/gcm.py
autopush/router/gcmclient.py
autopush/tests/test_gcmclient.py
autopush/tests/test_integration.py
autopush/tests/test_router.py

feat: assimilate the gcm client code

---

autopush/router/gcm.py
autopush/tests/test_endpoint.py
autopush/tests/test_gcmclient.py
autopush/tests/test_integration.py
autopush/tests/test_router.py

Issue #1068 
(Still a few integration tests out of whack after the gcmclient integration. Plus a bit of code tidying.)

bug: fix up tests and integration for new gcmclient

---

autopush/router/apnsrouter.py
autopush/tests/test_integration.py
autopush/tests/test_router.py

bug: Update APNs APS block

---

autopush/router/apnsrouter.py
autopush/tests/test_router.py

not clear why this one occurs so metric it for now vs bothering sentry
Issue: #1048

fix: handle an obscure SSLError seen w/ apns

---

autopush/tests/__init__.py
autopush/tests/test_integration.py
autopush/web/webpush.py

also quiet boto3's logging for tests
Closes: #1059

fix: use the right channel_id value in client_info

---

automock/boto.cfg
autopush/db.py
autopush/webpush_server.py
autopush_rs/Cargo.lock
autopush_rs/Cargo.toml
autopush_rs/src/client.rs
autopush_rs/src/lib.rs
autopush_rs/src/server/mod.rs
autopush_rs/src/util/autojson.rs
autopush_rs/src/util/mod.rs

feat: use structured logging and log session info out

---

autopush_rs/src/call.rs
autopush_rs/src/client.rs
autopush_rs/src/protocol.rs

feat: track nack's with metrics

---

autopush_rs/src/client.rs

feat: add error information for debugging connection drops

---

autopush/memusage.py
autopush/tests/test_integration.py
requirements.in

feat: include glibc malloc & jemalloc stats in memusage

---

autopush_rs/src/client.rs
autopush_rs/src/http.rs
autopush_rs/src/server/mod.rs

Refactors the HTTP handling slightly for easier additions in the
future.
Closes #1062

feat: add /notif/ HTTP API handler

---

autopush/utils.py
autopush_rs/Cargo.lock
autopush_rs/src/client.rs

update Cargo.lock (I think the latest cargo is changing the output?)
and a small doc fix

refactor: minor cleanup to shutdown

---

autopush/db.py
autopush/tests/test_db.py
autopush/tests/test_diagnostic_cli.py
autopush/tests/test_health.py
autopush/tests/test_integration.py
autopush/tests/test_websocket.py
autopush/web/health.py

feat: convert `table()` to variable for Message and Router classes

---

autopush/main.py
autopush/metrics.py
autopush/tests/test_metrics.py

bug: Restore periodicreporter after complex merge dropped it.

---

autopush/main.py
autopush_rs/Cargo.lock
autopush_rs/Cargo.toml
autopush_rs/__init__.py
autopush_rs/src/client.rs
autopush_rs/src/util/mod.rs
autopush_rs/src/util/user_agent.rs

relies on cadence dev w/ new tag support
also:
move ua parsing into utils w/ setup of metrics' specific values and
revert a stray pdb.set_trace
Closes #1054

feat: add metric tags

---

autopush/db.py
autopush/tests/test_db.py
autopush/utils.py

bug: Use environment var AWS_DEFAULT_REGION as region specifier

---

autopush/main.py
autopush/tests/test_rs_integration.py
autopush/webpush_server.py
autopush_rs/src/errors.rs
autopush_rs/src/server/mod.rs

also include the rust sentry thread in the shutdown process and fix
pulling SENTRY_DSN from build vs runtime env
Closes #1090

fix: make autopush_rs's ctrl-c work gracefully

---

autopush_rs/src/client.rs

feat: drain pending notifications from the client rx queue

---

autopush/router/apns2.py
autopush/router/apnsrouter.py
autopush/tests/test_db.py
autopush/tests/test_router.py
autopush/tests/test_web_base.py
autopush/tests/test_websocket.py
autopush/web/base.py
autopush/websocket.py

bug: Silence remaining nuisance alarms

---

autopush/main.py
autopush/memusage.py
autopush/ssl.py
autopush/tests/test_db.py
autopush/tests/test_rs_integration.py

refactor: rearrange/hack back to 100% coverage

---

autopush_rs/src/util/megaphone.rs
autopush_rs/src/util/mod.rs

feat: add megaphone service change tracker

---

autopush/router/gcm.py
autopush/router/gcmclient.py

bug remove GCM collapse key

---

autopush/router/webpush.py

bug: Handle PotentialDataLoss error

---

autopush/webpush_server.py

bug: Add ClientError handler to UnregisterCommand

---

autopush/config.py
autopush/main.py
autopush/tests/test_integration.py
autopush/tests/test_rs_integration.py
autopush_rs/Cargo.lock
autopush_rs/Cargo.toml
autopush_rs/__init__.py
autopush_rs/src/server/mod.rs
autopush_rs/src/util/mod.rs

feat: add megaphone integration tests

---

autopush/db.py
autopush/tests/test_db.py
autopush/web/registration.py

bug: Remove expiry checks for routing to prevent dropped mobile UAID

---

autopush/config.py
autopush/main.py
autopush/main_argparse.py
autopush/tests/test_rs_integration.py
autopush_rs/__init__.py
autopush_rs/src/server/mod.rs
autopush_rs/src/util/megaphone.rs
configs/autopush_connection.ini.sample

feat: add megaphone api token auth

---

autopush_rs/src/client.rs

WaitingForAck's was essentially identical to Await, except it allowed
for Ack's to come in. Combining these reduces duplication and errors
that may occur as a result while simplifying command handling.
Closes #1165

feat: refactor client to remove duplicate logic

---

autopush_rs/src/server/dispatch.rs
autopush_rs/src/server/mod.rs

feat: add a crit log_check to autopush_rs

---

autopush_rs/src/server/mod.rs
autopush_rs/src/util/mod.rs

fix: disable the logger guard for now

---

autopush/tests/test_integration.py
autopush_rs/src/client.rs

fix: return simple uaid to hello

---

autopush_rs/Cargo.toml
autopush_rs/src/client.rs
autopush_rs/src/util/mod.rs

feat: use chrono epoch times instead of monotonic time

---

autopush/tests/test_rs_integration.py

bug: sync endpoint and connection settings during integration testing

---

autopush/db.py

bug: Remove unused "expiry" from Router table

---

autopush/tests/test_websocket.py
autopush/websocket.py

fix: properly catch a null value passed to register

---

autopush/db.py
autopush/tests/test_rs_integration.py
autopush/tests/test_webpush_server.py
autopush/web/registration.py
autopush/webpush_server.py
autopush/websocket.py
autopush_rs/Cargo.lock
autopush_rs/Cargo.toml
autopush_rs/__init__.py
autopush_rs/src/call.rs
autopush_rs/src/client.rs
autopush_rs/src/lib.rs
autopush_rs/src/server/mod.rs
autopush_rs/src/util/ddb_helpers.rs
autopush_rs/src/util/mod.rs
autopush_rs/src/util/timing.rs

Co-authored by: Phil Jenvey <pjenvey@underboss.org>
Closes #1188

feat: port hello command to Rust

---

autopush_rs/src/client.rs
autopush_rs/src/protocol.rs

fix: reject unhyphenated channelIDs from register

---

autopush/tests/test_webpush_server.py
autopush/webpush_server.py
autopush_rs/src/call.rs
autopush_rs/src/client.rs
autopush_rs/src/protocol.rs
autopush_rs/src/util/ddb_helpers.rs

feat: port delete command to Rust

---

autopush_rs/build.rs

silently remove autopush.h instead just in case cbindgen fails when rustc
doesn't (to indicate something went wrong)
Closes #1235

fix: let the build continue to rustc on cbindgen failures

---

.travis.yml

chore: avoid cargo build within tox

---

autopush_rs/src/db/commands.rs
autopush_rs/src/db/mod.rs
autopush_rs/src/db/models.rs
autopush_rs/src/db/util.rs

and some minor changes
Issue #1238

refactor: remove/rearrange some clones

---

autopush_rs/src/db/commands.rs
autopush_rs/src/db/mod.rs

refactor: minor cleanup, then impl trait and box killing

---

autopush/tests/test_integration.py
autopush/tests/test_rs_integration.py

feat: add Rust + Python mixed integration tests

---

Dockerfile
Dockerfile.python27

Issue #1253
(merging to release/1.47)

fix: actually pass thru $WITH_RUST

---

autopush/main_argparse.py

fix: add env_vars for cmd line args missing them

---

autopush/tests/test_integration.py
autopush/tests/test_utils.py
autopush/websocket.py
requirements.in
requirements.txt

also fix missing ua_os/browser_ver fields in the session stats
Closes #1270

feat: update dependencies

---

autopush/tests/test_integration.py
autopush/web/webpush.py

fix: disallow negative ttls

---

autopush/router/gcm.py

fix: timeout gcm calls

---

Dockerfile
autopush/memusage.py
autopush/router/gcm.py
autopush/tests/test_integration.py
docs/http.rst

and include its new gc.get_stats in memusage
Closes #1288

feat: upgrade to pypy6 for debug symbols

---

requirements.in
requirements.txt

chore: upgrade dependencies

---

requirements.txt

chore: upgrade requests per CVE-2018-18074

---

autopush/db.py
autopush/tests/test_db.py

Issue: 103
More a WIP right now.

feat: Remove unused secondary global index

---

autopush/config.py
autopush/main_argparse.py
autopush/router/gcm.py
autopush/tests/test_endpoint.py
autopush/tests/test_integration.py
autopush/tests/test_router.py
autopush/tests/test_z_main.py

feat: add gcm endpoint configuration argument

---

autopush/tests/test_router.py
test-requirements.txt
tox.ini

chore: flake8

---

autopush/db.py
autopush/tests/test_db.py

* Fix tests to match how UAID is presented to functions.
Closes #1330

bug: Fix all_channels to match registration UAID format

---

autopush/tests/test_web_validation.py
autopush/web/webpush.py

bug: Check if the JWT contains a valid claim set.

---

autopush/config.py
autopush/tests/test_cryptokey.py
autopush/tests/test_db.py
autopush/tests/test_fcmclient.py
autopush/tests/test_gcmclient.py
autopush/tests/test_router.py
autopush/tests/test_web_validation.py
autopush/web/base.py
autopush/web/health.py
autopush/web/registration.py

exc.message -> str(exc)
attr's convert kw arg -> converter
Closes #1341

refactor: clear up deprecation warnings

---

autopush/router/adm.py
autopush/tests/test_integration.py

bug: Return correct status code/errno for ADM auth failures

---

autopush/tests/support.py
autopush/tests/test_client.py
autopush/tests/test_health.py
autopush/tests/test_integration.py
autopush/tests/test_log_check.py
requirements.txt

also rename non-Test classes to hide from py.test capture
Issue #1358

chore: update twisted per CVE-2019-12855

---

PULL_REQUEST_TEMPLATE.md
test-requirements.txt

Adding PR template to make repos consistent
N/A - Github template.
Closes #1376 .

chore: Add pull request template

---

README.md

remove requires.io for now which we don't have setup
Issue https://github.com/mozilla-services/services-engineering/issues/3

chore: add a matrix badge

---

CHANGELOG.md
autopush/__init__.py

This is an old release branch but forgot to bring its CHANGELOG over

chore: tag 1.54.2

---

CHANGELOG.md
autopush/__init__.py

chore: tag 1.55.2

---

autopush/tests/test_integration.py
autopush/utils.py

* Remove embedded " and = from Encryption and Crypto-Key header values
testing included. 
Closes #1419

bug: fix header_cleanup for aesgcm

---

autopush/router/adm.py
autopush/router/fcm_v1.py

Closes #1426
converts instances of `reason` tag to use snake_case, corrects spelling mistake.
verify below
Closes #1426

bug: normalize `reason` tag to snake_case

---

autopush/tests/test_integration.py
autopush/tests/test_web_validation.py
autopush/web/webpush.py

Closes: bug 1663922
Enforce VAPID `aud` compliance.
Tests are included in patch
Closes [1663922](https://bugzilla.mozilla.org/show_bug.cgi?id=1663922)

bug: enforce VAPID "aud" compliance.

---

.circleci/config.yml
test-requirements.txt

Issue: https://github.com/mozilla-services/services-engineering/issues/71

chore: update circleci to use new docker auth

---

requirements.txt

Dependency update for March 2021

chore: Update for Mar 2021

---

README.md

Autopush-rs is the new repo. This repo can be retired.

chore: retire repo.
